Gobelijn API documentation: ODemo::WaterVehicle Class Reference
ODemo::WaterVehicle Class Reference abstract
Abstract WaterVehicle class.
#include <WaterVehicle.h>
Public Member Functions
WaterVehicle ()
Default constructor.
WaterVehicle (const WaterVehicle &ori)
Copy constructor.
WaterVehicle (WaterVehicle &&ori) noexcept
Move constructor.
WaterVehicle & operator= (const WaterVehicle &rhs)
Copy assignment.
WaterVehicle & operator= (WaterVehicle &&rhs) noexcept
Move assignment.
~WaterVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override=0
Pure virtual method for motion.
void start_sinking ()
Start sinking, even if you are already sinking.
void stop_sinking ()
Stop sinking, even if you were not sinking in the first place.
Public Member Functions inherited from ODemo::Vehicle
virtual ~Vehicle ()=default
Destructor.
Private Attributes
bool m_sinking
Detailed Description
Abstract WaterVehicle class.
Definition at line 15 of file WaterVehicle.h.
Constructor & Destructor Documentation
WaterVehicle() [1/3]
ODemo::WaterVehicle::WaterVehicle ()
Default constructor.
Definition at line 14 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
WaterVehicle() [2/3]
ODemo::WaterVehicle::WaterVehicle (const WaterVehicle & ori)
Copy constructor.
Definition at line 16 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
WaterVehicle() [3/3]
ODemo::WaterVehicle::WaterVehicle (WaterVehicle && ori) noexcept
Move constructor.
Definition at line 21 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
~WaterVehicle()
ODemo::WaterVehicle::~WaterVehicle () override
Destructor.
Definition at line 46 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
WaterVehicle & ODemo::WaterVehicle::operator= (const WaterVehicle & rhs)
Copy assignment.
Definition at line 26 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_sinking.
Referenced by ODemo::SailBoat::operator=().
operator=() [2/2]
WaterVehicle & ODemo::WaterVehicle::operator= (WaterVehicle && rhs) noexcept
Move assignment.
Definition at line 36 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
info()
void ODemo::WaterVehicle::info () const override virtual
Return identification info.
Implements ODemo::Vehicle.
Definition at line 48 of file WaterVehicle.cpp.
References COMP_MISC_LOG_TRACER, COMP_MISC_MEMBER_TRACER, and m_sinking.
move()
void ODemo::WaterVehicle::move (double speed, std::vector< double > direction) override pure virtual
Pure virtual method for motion.
Implements ODemo::Vehicle.
Implemented in ODemo::SailBoat.
start_sinking()
void ODemo::WaterVehicle::start_sinking ()
Start sinking, even if you are already sinking.
Definition at line 58 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_sinking.
Referenced by app_exception(), and app_hierarchies().
stop_sinking()
void ODemo::WaterVehicle::stop_sinking ()
Stop sinking, even if you were not sinking in the first place.
Definition at line 64 of file WaterVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_sinking.
Member Data Documentation
m_sinking
bool ODemo::WaterVehicle::m_sinking private
Definition at line 49 of file WaterVehicle.h.
Referenced by info(), operator=(), start_sinking(), and stop_sinking().
The documentation for this class was generated from the following files:
WaterVehicle.h
WaterVehicle.cpp