Gobelijn API documentation: ODemo::SailBoat Class Reference
ODemo::SailBoat Class Reference
A simple SailBoat class.
#include <SailBoat.h>
Public Member Functions
SailBoat (std::string name)
Parametrized constructor initializes the name of the boat.
SailBoat (const SailBoat &ori)
Copy constructor.
SailBoat (SailBoat &&ori) noexcept
Move constructor.
SailBoat & operator= (const SailBoat &rhs)
Copy assignment.
SailBoat & operator= (SailBoat &&rhs) noexcept
Move assignment.
~SailBoat () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Sailboat motion.
Public Member Functions inherited from ODemo::WaterVehicle
WaterVehicle ()
Default constructor.
WaterVehicle (const WaterVehicle &ori)
Copy constructor.
WaterVehicle (WaterVehicle &&ori) noexcept
Move constructor.
WaterVehicle & operator= (const WaterVehicle &rhs)
Copy assignment.
WaterVehicle & operator= (WaterVehicle &&rhs) noexcept
Move assignment.
~WaterVehicle () override
Destructor.
void info () const override
Return identification info.
void start_sinking ()
Start sinking, even if you are already sinking.
void stop_sinking ()
Stop sinking, even if you were not sinking in the first place.
Public Member Functions inherited from ODemo::Vehicle
virtual ~Vehicle ()=default
Destructor.
Private Attributes
std::string m_name
bool m_sails_up
Detailed Description
A simple SailBoat class.
Definition at line 15 of file SailBoat.h.
Constructor & Destructor Documentation
SailBoat() [1/3]
ODemo::SailBoat::SailBoat (std::string name) explicit
Parametrized constructor initializes the name of the boat.
Definition at line 14 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER.
SailBoat() [2/3]
ODemo::SailBoat::SailBoat (const SailBoat & ori)
Copy constructor.
Definition at line 19 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER.
SailBoat() [3/3]
ODemo::SailBoat::SailBoat (SailBoat && ori) noexcept
Move constructor.
Definition at line 24 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER.
~SailBoat()
ODemo::SailBoat::~SailBoat () override
Destructor.
Definition at line 52 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
SailBoat & ODemo::SailBoat::operator= (const SailBoat & rhs)
Copy assignment.
Definition at line 30 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER, m_name, m_sails_up, and ODemo::WaterVehicle::operator=().
operator=() [2/2]
SailBoat & ODemo::SailBoat::operator= (SailBoat && rhs) noexcept
Move assignment.
Definition at line 41 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER, and ODemo::WaterVehicle::operator=().
info()
void ODemo::SailBoat::info () const override virtual
Return identification info.
Implements ODemo::Vehicle.
Definition at line 54 of file SailBoat.cpp.
References COMP_MISC_LOG_TRACER, COMP_MISC_MEMBER_TRACER, m_name, and m_sails_up.
Referenced by app_exception(), and app_hierarchies().
move()
void ODemo::SailBoat::move (double speed, std::vector< double > direction) override virtual
Sailboat motion.
Implements ODemo::WaterVehicle.
Definition at line 66 of file SailBoat.cpp.
References COMP_MISC_MEMBER_TRACER, and m_sails_up.
Referenced by app_exception(), and app_hierarchies().
Member Data Documentation
m_name
std::string ODemo::SailBoat::m_name private
Definition at line 43 of file SailBoat.h.
Referenced by info(), and operator=().
m_sails_up
bool ODemo::SailBoat::m_sails_up private
Definition at line 44 of file SailBoat.h.
Referenced by info(), move(), and operator=().
The documentation for this class was generated from the following files:
SailBoat.h
SailBoat.cpp