Gobelijn API documentation: main.cpp File Reference
raii/files/main.cpp File Reference
Main using the RAII File class.
#include <cstdio>
#include <iostream>
#include "file.h"
Functions
void printFile (File &file)
Prints the contents of the given file.
int main ()
Detailed Description
Main using the RAII File class.
Definition in file raii/files/main.cpp.
Function Documentation
printFile()
void printFile (File & file)
Prints the contents of the given file.
Definition at line 30 of file raii/files/main.cpp.
References Raii::File::ReadChar().
Referenced by main().
main()
int main ()
Definition at line 38 of file raii/files/main.cpp.
References Raii::File::Close(), printFile(), and Raii::File::WriteChar().