Gobelijn API documentation: Stack< T > Class Template Reference
Stack< T > Class Template Reference
Stack class using vector as element container.
#include <stack1.hpp>
Public Member Functions
Stack ()
Default constructor.
bool empty () const
Check whether stack is empty.
void pop ()
Pop element off the stack.
void push (const T &e)
Pushes element onto stack.
T top () const
Return top element of the stack (but not pop-ing it).
Stack ()
Default constructor.
bool empty () const
Check whether stack is empty.
void pop ()
Pop element off the stack.
void push (const T &e)
Pushes element onto stack.
T top () const
Return top element of the stack (but not pop-ing it).
bool empty () const
Check whether stack is empty.
bool full () const
Check wheter stack is full.
void pop ()
Pop element off the stack.
void push (const T &e)
Pushes element onto stack.
T top () const
Return top element of the stack (but not pop-ing it).
Stack ()
Default constructor.
template<typename T2 >
Stack< T > & operator= (const Stack< T2 > &rhs)
Assignment of one stack to another.
bool empty () const
Check whether stack is empty.
void pop ()
Pop element off the stack.
void push (const T &e)
Pushes element onto stack.
T top () const
Return top element of the stack (but not pop-ing it).
Stack ()
Default constructor.
template<typename T2 , typename CONT2 >
Stack< T, CONT > & operator= (Stack< T2, CONT2 > const &)
Assignment of one stack to another.
bool empty () const
Check whether stack is empty.
void pop ()
Pop element off the stack.
void push (const T &e)
Pushes element onto stack.
T top () const
Return top element of the stack (but not pop-ing it).
Stack ()
Default constructor.
bool empty () const
Check whether stack is empty.
void pop ()
Pop element off the stack.
void push (const T &e)
Pushes element onto stack.
T top () const
Return top element of the stack (but not pop-ing it).
Private Attributes
std::vector< T > elems
Container for the stack elements.
CONT elems
Container for the stack elements.
T elems [MAXSIZE]
Array to caontain stack elements.
unsigned int numElems {0}
Current number of elements.
std::deque< T > elems
Container for the stack elements.
CONT< T, ALLOC > elems
Container for the stack elements.
Detailed Description
template<typename T>
class Stack< T >
Stack class using vector as element container.
Stack template.
Stack class using dequeue as element container.
Template Parameters
T Template param for element type.
T Template param for element type.
CONT Container type fo stack elements.
T Template param for element type.
MAXSIZE Maximum capacity of the container.
T template param for element type.
T Template param for element.
CONT Template param for container for elements.
T Template param for element.
ALLOC Allocator for the stack container.
CONT Template param for container for elements.
Definition at line 15 of file stack1.hpp.
Constructor & Destructor Documentation
Stack() [1/5]
template<typename T > Stack< T >::Stack () inline
Default constructor.
Definition at line 19 of file stack1.hpp.
Stack() [2/5]
template<typename T > Stack< T >::Stack () inline
Default constructor.
Definition at line 20 of file stack3.hpp.
Stack() [3/5]
template<typename T > Stack< T >::Stack () inline
Default constructor.
Definition at line 18 of file stack5.hpp.
Stack() [4/5]
template<typename T > Stack< T >::Stack () inline
Default constructor.
Definition at line 19 of file stack6.hpp.
Stack() [5/5]
template<typename T > Stack< T >::Stack () inline
Default constructor.
Definition at line 20 of file stack7.hpp.
Member Function Documentation
empty() [1/6]
template<typename T > bool Stack< T >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 23 of file stack1.hpp.
References Stack< T >::elems.
Referenced by Stack< T >::operator=().
pop() [1/6]
template<typename T , typename ALLOC , template< typename, typename > class CONT> void Stack< T, ALLOC, CONT >::pop
Pop element off the stack.
Definition at line 43 of file stack1.hpp.
Referenced by main(), and Stack< T >::operator=().
push() [1/6]
template<typename T , typename ALLOC , template< typename, typename > class CONT> void Stack< T, ALLOC, CONT >::push (const T & e)
Pushes element onto stack.
Parameters
e Element to be pushed onto stack.
Definition at line 52 of file stack1.hpp.
Referenced by main().
top() [1/6]
template<typename T , typename ALLOC , template< typename, typename > class CONT> T Stack< T, ALLOC, CONT >::top
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack.
Definition at line 58 of file stack1.hpp.
Referenced by main(), and Stack< T >::operator=().
empty() [2/6]
template<typename T > bool Stack< T >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 24 of file stack3.hpp.
References Stack< T >::elems.
pop() [2/6]
template<typename T > void Stack< T >::pop ()
Pop element off the stack.
push() [2/6]
template<typename T > void Stack< T >::push (const T & e)
Pushes element onto stack.
Parameters
e Element to be pushed onto stack.
top() [2/6]
template<typename T > T Stack< T >::top () const
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack.
empty() [3/6]
template<typename T > bool Stack< T >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 19 of file stack4.hpp.
References Stack< T >::numElems.
full()
template<typename T > bool Stack< T >::full () const inline
Check wheter stack is full.
Returns
True iff full.
Definition at line 23 of file stack4.hpp.
References Stack< T >::numElems.
pop() [3/6]
template<typename T > void Stack< T >::pop ()
Pop element off the stack.
push() [3/6]
template<typename T > void Stack< T >::push (const T & e)
Pushes element onto stack.
Parameters
e Element to be pushed onto stack.
top() [3/6]
template<typename T > T Stack< T >::top () const
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack.
operator=() [1/2]
template<typename T > template<typename T2 > Stack< T > & Stack< T >::operator= (const Stack< T2 > & rhs)
Assignment of one stack to another.
Template Parameters
T2 Template param for element type of rhs stack.
Returns
reference to the stack.
Definition at line 49 of file stack5.hpp.
References Stack< T >::empty(), Stack< T >::pop(), and Stack< T >::top().
empty() [4/6]
template<typename T > bool Stack< T >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 28 of file stack5.hpp.
References Stack< T >::elems.
pop() [4/6]
template<typename T > void Stack< T >::pop ()
Pop element off the stack.
push() [4/6]
template<typename T > void Stack< T >::push (const T & e)
Pushes element onto stack.
Parameters
e Element to be pushed onto stack.
top() [4/6]
template<typename T > T Stack< T >::top () const
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack.
operator=() [2/2]
template<typename T , typename CONT > template<typename T2 , typename CONT2 > Stack< T, CONT > & Stack< T, CONT >::operator= (Stack< T2, CONT2 > const & op2)
Assignment of one stack to another.
Template Parameters
T2 Template param for element type of rhs stack.
Returns
reference to the stack.
Definition at line 50 of file stack6.hpp.
References Stack< T >::empty(), Stack< T >::pop(), and Stack< T >::top().
empty() [5/6]
template<typename T > bool Stack< T >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 29 of file stack6.hpp.
References Stack< T >::elems.
pop() [5/6]
template<typename T > void Stack< T >::pop ()
Pop element off the stack.
push() [5/6]
template<typename T > void Stack< T >::push (const T & e)
Pushes element onto stack.
Parameters
e Element to be pushed onto stack
top() [5/6]
template<typename T > T Stack< T >::top () const
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack
empty() [6/6]
template<typename T > bool Stack< T >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 24 of file stack7.hpp.
References Stack< T >::elems.
pop() [6/6]
template<typename T > void Stack< T >::pop ()
Pop element off the stack.
push() [6/6]
template<typename T > void Stack< T >::push (const T & e)
Pushes element onto stack.
Parameters
e Element to be pushed onto stack.
top() [6/6]
template<typename T > T Stack< T >::top () const
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack.
Member Data Documentation
elems [1/5]
template<typename T > CONT Stack< T >::elems private
Container for the stack elements.
Definition at line 37 of file stack1.hpp.
Referenced by Stack< T >::empty(), Stack< std::string >::empty(), Stack< std::string >::pop(), Stack< std::string >::push(), and Stack< std::string >::top().
elems [2/5]
template<typename T > CONT Stack< T >::elems private
Container for the stack elements.
Definition at line 38 of file stack3.hpp.
elems [3/5]
template<typename T > T Stack< T >::elems[MAXSIZE] private
Array to caontain stack elements.
Definition at line 37 of file stack4.hpp.
numElems
template<typename T > unsigned int Stack< T >::numElems {0} private
Current number of elements.
Definition at line 38 of file stack4.hpp.
Referenced by Stack< T >::empty(), and Stack< T >::full().
elems [4/5]
template<typename T > std::deque<T> Stack< T >::elems private
Container for the stack elements.
Definition at line 42 of file stack5.hpp.
elems [5/5]
template<typename T > CONT<T, ALLOC> Stack< T >::elems private
Container for the stack elements.
Definition at line 38 of file stack7.hpp.
The documentation for this class was generated from the following files:
stack1.hpp
stack3.hpp
stack4.hpp
stack5.hpp
stack6.hpp
stack7.hpp