Gobelijn API documentation: ODemo::Bicycle Class Reference
ODemo::Bicycle Class Reference
Represents a simple Bicycle.
#include <Bicycle.h>
Public Member Functions
Bicycle ()
Default constructor.
Bicycle (std::string model, std::string color)
Parametrized contructor, initialize model and color.
Bicycle (const Bicycle &ori)
Copy constructor.
Bicycle (Bicycle &&ori) noexcept
Move constructor.
Bicycle & operator= (const Bicycle &rhs)
Copy assignment.
Bicycle & operator= (Bicycle &&rhs) noexcept
Move assignment.
~Bicycle () override
Destructor.
std::string getModel () const
Return the model of the bike.
std::string getColor () const
Return the color of the bike.
void setModel (std::string model)
Set the model of the bike.
void setColor (std::string color)
Set the color of the bike.
void info () const override
Display info on model and color of the bike.
Public Member Functions inherited from ODemo::PassengerRoadVehicle
PassengerRoadVehicle (int numSeats)
Parametrized constructor, initializes number of seats.
PassengerRoadVehicle (PassengerRoadVehicle const &ori)
Copy constructor.
PassengerRoadVehicle (PassengerRoadVehicle &&ori) noexcept
Move constructor.
PassengerRoadVehicle & operator= (PassengerRoadVehicle const &rhs)
Copy assignment.
PassengerRoadVehicle & operator= (PassengerRoadVehicle &&rhs) noexcept
Move assignment.
~PassengerRoadVehicle () override
Destructor.
bool add_passenger ()
Take an additional passenger on board, if possible.
bool remove_passenger ()
Remove a passenger, if possible.
int get_capacity () const
Return the number of seats on the vehicle.
int get_free () const
Return the number of seats still free.
void info () const override
Return identification info.
Public Member Functions inherited from ODemo::RoadVehicle
RoadVehicle ()
Default constructor.
RoadVehicle (const RoadVehicle &ori)
Copy constructor.
RoadVehicle (RoadVehicle &&ori) noexcept
Move constructor.
RoadVehicle & operator= (const RoadVehicle &rhs)
Copy assignment operator.
RoadVehicle & operator= (RoadVehicle &&rhs) noexcept
Move assignment operator.
~RoadVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Motion of the vehicle.
Public Member Functions inherited from ODemo::LandVehicle
LandVehicle ()
default constructor.
LandVehicle (const LandVehicle &ori)
Copy constructor.
LandVehicle (LandVehicle &&ori) noexcept
Move constructor.
LandVehicle & operator= (const LandVehicle &rhs)
Copy assignment.
LandVehicle & operator= (LandVehicle &&rhs) noexcept
Move assignment.
~LandVehicle () override
Destructor.
Public Member Functions inherited from ODemo::Vehicle
virtual ~Vehicle ()=default
Destructor.
Private Attributes
std::string m_model
std::string m_color
Detailed Description
Represents a simple Bicycle.
Definition at line 16 of file Bicycle.h.
Constructor & Destructor Documentation
Bicycle() [1/4]
ODemo::Bicycle::Bicycle ()
Default constructor.
Definition at line 14 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER.
Bicycle() [2/4]
ODemo::Bicycle::Bicycle (std::string model, std::string color)
Parametrized contructor, initialize model and color.
Definition at line 19 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER.
Bicycle() [3/4]
ODemo::Bicycle::Bicycle (const Bicycle & ori)
Copy constructor.
Definition at line 25 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER.
Bicycle() [4/4]
ODemo::Bicycle::Bicycle (Bicycle && ori) noexcept
Move constructor.
Definition at line 30 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER.
~Bicycle()
ODemo::Bicycle::~Bicycle () override
Destructor.
Definition at line 62 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
Bicycle & ODemo::Bicycle::operator= (const Bicycle & rhs)
Copy assignment.
Definition at line 36 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER, m_color, m_model, and ODemo::PassengerRoadVehicle::operator=().
operator=() [2/2]
Bicycle & ODemo::Bicycle::operator= (Bicycle && rhs) noexcept
Move assignment.
Definition at line 47 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER, and ODemo::PassengerRoadVehicle::operator=().
getModel()
string ODemo::Bicycle::getModel () const
Return the model of the bike.
Definition at line 64 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_model.
getColor()
string ODemo::Bicycle::getColor () const
Return the color of the bike.
Definition at line 70 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_color.
setModel()
void ODemo::Bicycle::setModel (std::string model)
Set the model of the bike.
Definition at line 76 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_model.
setColor()
void ODemo::Bicycle::setColor (std::string color)
Set the color of the bike.
Definition at line 82 of file Bicycle.cpp.
References COMP_MISC_MEMBER_TRACER, and m_color.
info()
void ODemo::Bicycle::info () const override virtual
Display info on model and color of the bike.
Implements ODemo::Vehicle.
Definition at line 88 of file Bicycle.cpp.
References COMP_MISC_LOG_TRACER, COMP_MISC_MEMBER_TRACER, m_color, and m_model.
Referenced by app_exception(), and app_hierarchies().
Member Data Documentation
m_model
std::string ODemo::Bicycle::m_model private
Definition at line 56 of file Bicycle.h.
Referenced by getModel(), info(), operator=(), and setModel().
m_color
std::string ODemo::Bicycle::m_color private
Definition at line 57 of file Bicycle.h.
Referenced by getColor(), info(), operator=(), and setColor().
The documentation for this class was generated from the following files:
Bicycle.h
Bicycle.cpp