Gobelijn API documentation: tracing_example_exam::Rentable Class Reference
tracing_example_exam::Rentable Class Reference
#include <Rentable.h>
Public Member Functions
Rentable ()
Constructor.
Rentable (const Rentable &r)
Copy Constructor.
Rentable (Rentable &&r)
Move Constructor.
virtual ~Rentable ()
Destructor.
Rentable & operator= (const Rentable &)
Copy-assignment of a Rentable:
Rentable & operator= (Rentable &&)
Move-assignment of a Rentable:
void rent (Person &renter)
Rent this Rentable.
Private Attributes
std::shared_ptr< Person > m_renter
Detailed Description
Definition at line 18 of file Rentable.h.
Constructor & Destructor Documentation
Rentable() [1/3]
tracing_example_exam::Rentable::Rentable ()
Constructor.
Definition at line 15 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER.
Rentable() [2/3]
tracing_example_exam::Rentable::Rentable (const Rentable & r)
Copy Constructor.
Definition at line 19 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER.
Rentable() [3/3]
tracing_example_exam::Rentable::Rentable (Rentable && r)
Move Constructor.
Definition at line 21 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER.
~Rentable()
tracing_example_exam::Rentable::~Rentable () virtual
Destructor.
Definition at line 17 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
Rentable & tracing_example_exam::Rentable::operator= (const Rentable & other)
Copy-assignment of a Rentable:
Definition at line 23 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER, and m_renter.
Referenced by tracing_example_exam::HolidayHome::operator=().
operator=() [2/2]
Rentable & tracing_example_exam::Rentable::operator= (Rentable && other)
Move-assignment of a Rentable:
Definition at line 32 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER, and m_renter.
rent()
void tracing_example_exam::Rentable::rent (Person & renter)
Rent this Rentable.
Definition at line 41 of file Rentable.cpp.
References COMP_MISC_MEMBER_TRACER, and m_renter.
Referenced by app_example_exam_2021_1(), and app_example_exam_2021_2().
Member Data Documentation
m_renter
std::shared_ptr<Person> tracing_example_exam::Rentable::m_renter private
Definition at line 43 of file Rentable.h.
Referenced by operator=(), and rent().
The documentation for this class was generated from the following files:
Rentable.h
Rentable.cpp