Gobelijn API documentation: main.cpp File Reference
raii/random-read-files/main.cpp File Reference
Main using the RAII random read file class.
#include <iostream>
#include "../files/file.h"
#include "random-read-file.h"
Functions
void tacFile (const RandomReadFile &raFile)
int main ()
Detailed Description
Main using the RAII random read file class.
Definition in file raii/random-read-files/main.cpp.
Function Documentation
tacFile()
void tacFile (const RandomReadFile & raFile)
Definition at line 28 of file raii/random-read-files/main.cpp.
Referenced by main().
main()
int main ()
Definition at line 39 of file raii/random-read-files/main.cpp.
References tacFile(), and Raii::File::WriteChar().