Gobelijn API documentation: UA_CoMP::Container::SegmentedVector< T, N > Class Template Reference
UA_CoMP::Container::SegmentedVector< T, N > Class Template Reference
Container that stores objects "almost contiguously" and guarantees that pointers/iterators are not invalidated when the container grows, either through push_back/emplace_back of elements or resevation of capacity.
#include <SegmentedVector.h>
Public Types
using value_type = T
using size_type = std::size_t
using self_type = SegmentedVector< T, N >
using iterator = SVIterator< T, N, T *, T &, false >
using const_iterator = SVIterator< T, N >
Public Member Functions
SegmentedVector ()
Construct empty SegmentedVector.
SegmentedVector (const self_type &other)
Copy constructor (copies elements & capacity).
SegmentedVector (self_type &&other) noexcept
Move constructor (moves elements & capacity).
SegmentedVector & operator= (const self_type &other)
Copy assignment (copies elements & capacity).
SegmentedVector & operator= (self_type &&other) noexcept
Move assignment (copies elements & capacity).
~SegmentedVector ()
Destructor.
T & at (std::size_t pos)
Access specified element with bounds checking.
const T & at (std::size_t pos) const
Access specified element with bounds checking.
T & back ()
Access the last element.
const T & back () const
Access the last element.
T & operator[] (size_t pos)
Access specified element (no bounds checking).
const T & operator[] (size_t pos) const
Access specified element (no bounds checking).
iterator begin ()
Returns an iterator to the beginning of the container.
const_iterator begin () const
Returns a const_iterator to the beginning of the container.
const_iterator cbegin () const
Returns a const_iterator to the beginning of the container.
iterator end ()
Returns an iterator to the end of the container.
const_iterator end () const
Returns a const_iterator to the end of the container.
const_iterator cend () const
Returns a const_iterator to the end.
std::size_t capacity () const
Returns number of elements that can be stored without allocating additional blocks.
bool empty () const
Checks whether container is empty.
std::size_t get_block_count () const
Returns number of currently allocated blocks.
std::size_t get_elements_per_block () const
Returns number of elements block (template parameter 'N').
std::size_t size () const
Returns the number of elements.
void reserve (size_type new_capacity)
Allocates aditional blocks to achieve requested capacity.
void shrink_to_fit ()
Deallocates (empty) blocks to schrink capacity to fit current size.
void clear ()
Clears the content.
template<class... Args>
T * emplace_back (Args &&... args)
Constructs element in-place at the end.
void pop_back ()
Removes the last element.
T * push_back (const T &obj)
Adds element to end.
T * push_back (T &&obj)
Adds element to end.
Private Types
using Chunk = typename std::aligned_storage< sizeof(T), std::alignment_of< T >::value >::type
POD type with same alignment requirement as for T's.
Private Member Functions
T * get_chunk ()
Get next available chunk for element construction with placement new.
Private Attributes
std::vector< Chunk * > m_blocks
Vector registers pointers to blocks of chunks.
size_t m_size
Index of first free chunk when indexed contiguously.
Friends
class SVIterator< T, N >
class SVIterator< T, N, T *, T &, false >
Detailed Description
template<typename T, size_t N = 512>
class UA_CoMP::Container::SegmentedVector< T, N >
Container that stores objects "almost contiguously" and guarantees that pointers/iterators are not invalidated when the container grows, either through push_back/emplace_back of elements or resevation of capacity.
It combines vector properties (high data locality) with queue properties (can increase capacity without pointer/iterator invalidation). Actually, its implementation is much like a queue but with a limited interface e.g. no insertions. The reason for the SegmentedVector is that one cannot control the block size for std:queue (where it is small) and we need that control to make the block size flexible and rather large.
Template parameters: T type of elements stored in the container N block size i.e. number of elements per block
Definition at line 51 of file SegmentedVector.h.
Member Typedef Documentation
value_type
template<typename T , size_t N = 512> using UA_CoMP::Container::SegmentedVector< T, N >::value_type = T
Definition at line 57 of file SegmentedVector.h.
size_type
template<typename T , size_t N = 512> using UA_CoMP::Container::SegmentedVector< T, N >::size_type = std::size_t
Definition at line 58 of file SegmentedVector.h.
self_type
template<typename T , size_t N = 512> using UA_CoMP::Container::SegmentedVector< T, N >::self_type = SegmentedVector<T, N>
Definition at line 59 of file SegmentedVector.h.
iterator
template<typename T , size_t N = 512> using UA_CoMP::Container::SegmentedVector< T, N >::iterator = SVIterator<T, N, T*, T&, false>
Definition at line 60 of file SegmentedVector.h.
const_iterator
template<typename T , size_t N = 512> using UA_CoMP::Container::SegmentedVector< T, N >::const_iterator = SVIterator<T, N>
Definition at line 61 of file SegmentedVector.h.
Chunk
template<typename T , size_t N = 512> using UA_CoMP::Container::SegmentedVector< T, N >::Chunk = typename std::aligned_storage<sizeof(T), std::alignment_of<T>::value>::type private
POD type with same alignment requirement as for T's.
Definition at line 285 of file SegmentedVector.h.
Constructor & Destructor Documentation
SegmentedVector() [1/3]
template<typename T , size_t N = 512> UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector () inline explicit
Construct empty SegmentedVector.
Definition at line 68 of file SegmentedVector.h.
SegmentedVector() [2/3]
template<typename T , size_t N = 512> UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector (const self_type & other) inline
Copy constructor (copies elements & capacity).
If excess capacity not needed, do shrink_to_fit.
Definition at line 72 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::capacity(), UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, UA_CoMP::Container::SegmentedVector< T, N >::m_size, UA_CoMP::Container::SegmentedVector< T, N >::push_back(), and UA_CoMP::Container::SegmentedVector< T, N >::reserve().
SegmentedVector() [3/3]
template<typename T , size_t N = 512> UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector (self_type && other) inline noexcept
Move constructor (moves elements & capacity).
If excess capacity not needed, do shrink_to_fit.
Definition at line 85 of file SegmentedVector.h.
~SegmentedVector()
template<typename T , size_t N = 512> UA_CoMP::Container::SegmentedVector< T, N >::~SegmentedVector () inline
Destructor.
Definition at line 120 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::clear().
Member Function Documentation
operator=() [1/2]
template<typename T , size_t N = 512> SegmentedVector & UA_CoMP::Container::SegmentedVector< T, N >::operator= (const self_type & other) inline
Copy assignment (copies elements & capacity).
If excess capacity not needed, do shrink_to_fit.
Definition at line 92 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::capacity(), UA_CoMP::Container::SegmentedVector< T, N >::clear(), UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, UA_CoMP::Container::SegmentedVector< T, N >::m_size, UA_CoMP::Container::SegmentedVector< T, N >::push_back(), and UA_CoMP::Container::SegmentedVector< T, N >::reserve().
operator=() [2/2]
template<typename T , size_t N = 512> SegmentedVector & UA_CoMP::Container::SegmentedVector< T, N >::operator= (self_type && other) inline noexcept
Move assignment (copies elements & capacity).
If excess capacity not needed, do shrink_to_fit.
Definition at line 109 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::clear(), UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
at() [1/2]
template<typename T , size_t N = 512> T & UA_CoMP::Container::SegmentedVector< T, N >::at (std::size_t pos) inline
Access specified element with bounds checking.
Definition at line 127 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::pop_back().
at() [2/2]
template<typename T , size_t N = 512> const T & UA_CoMP::Container::SegmentedVector< T, N >::at (std::size_t pos) const inline
Access specified element with bounds checking.
Definition at line 138 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
back() [1/2]
template<typename T , size_t N = 512> T & UA_CoMP::Container::SegmentedVector< T, N >::back () inline
Access the last element.
Definition at line 149 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
back() [2/2]
template<typename T , size_t N = 512> const T & UA_CoMP::Container::SegmentedVector< T, N >::back () const inline
Access the last element.
Definition at line 152 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
operator[]() [1/2]
template<typename T , size_t N = 512> T & UA_CoMP::Container::SegmentedVector< T, N >::operator[] (size_t pos) inline
Access specified element (no bounds checking).
Definition at line 158 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks.
operator[]() [2/2]
template<typename T , size_t N = 512> const T & UA_CoMP::Container::SegmentedVector< T, N >::operator[] (size_t pos) const inline
Access specified element (no bounds checking).
Definition at line 161 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks.
begin() [1/2]
template<typename T , size_t N = 512> iterator UA_CoMP::Container::SegmentedVector< T, N >::begin () inline
Returns an iterator to the beginning of the container.
Definition at line 171 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::end(), and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
begin() [2/2]
template<typename T , size_t N = 512> const_iterator UA_CoMP::Container::SegmentedVector< T, N >::begin () const inline
Returns a const_iterator to the beginning of the container.
Definition at line 174 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::end(), and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
cbegin()
template<typename T , size_t N = 512> const_iterator UA_CoMP::Container::SegmentedVector< T, N >::cbegin () const inline
Returns a const_iterator to the beginning of the container.
Definition at line 177 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::end(), and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
end() [1/2]
template<typename T , size_t N = 512> iterator UA_CoMP::Container::SegmentedVector< T, N >::end () inline
Returns an iterator to the end of the container.
Definition at line 180 of file SegmentedVector.h.
References UA_CoMP::Container::SVIterator< T, N, P, R, is_const_iterator >::m_end.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::begin(), and UA_CoMP::Container::SegmentedVector< T, N >::cbegin().
end() [2/2]
template<typename T , size_t N = 512> const_iterator UA_CoMP::Container::SegmentedVector< T, N >::end () const inline
Returns a const_iterator to the end of the container.
Definition at line 183 of file SegmentedVector.h.
References UA_CoMP::Container::SVIterator< T, N, P, R, is_const_iterator >::m_end.
cend()
template<typename T , size_t N = 512> const_iterator UA_CoMP::Container::SegmentedVector< T, N >::cend () const inline
Returns a const_iterator to the end.
Definition at line 186 of file SegmentedVector.h.
References UA_CoMP::Container::SVIterator< T, N, P, R, is_const_iterator >::m_end.
capacity()
template<typename T , size_t N = 512> std::size_t UA_CoMP::Container::SegmentedVector< T, N >::capacity () const inline
Returns number of elements that can be stored without allocating additional blocks.
Definition at line 193 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector(), UA_CoMP::Container::SegmentedVector< T, N >::operator=(), and UA_CoMP::Container::SegmentedVector< T, N >::reserve().
empty()
template<typename T , size_t N = 512> bool UA_CoMP::Container::SegmentedVector< T, N >::empty () const inline
Checks whether container is empty.
Definition at line 196 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_size.
get_block_count()
template<typename T , size_t N = 512> std::size_t UA_CoMP::Container::SegmentedVector< T, N >::get_block_count () const inline
Returns number of currently allocated blocks.
Definition at line 199 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks.
get_elements_per_block()
template<typename T , size_t N = 512> std::size_t UA_CoMP::Container::SegmentedVector< T, N >::get_elements_per_block () const inline
Returns number of elements block (template parameter 'N').
Definition at line 202 of file SegmentedVector.h.
size()
template<typename T , size_t N = 512> std::size_t UA_CoMP::Container::SegmentedVector< T, N >::size () const inline
Returns the number of elements.
Definition at line 205 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_size.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::shrink_to_fit().
reserve()
template<typename T , size_t N = 512> void UA_CoMP::Container::SegmentedVector< T, N >::reserve (size_type new_capacity) inline
Allocates aditional blocks to achieve requested capacity.
Definition at line 212 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::capacity(), and UA_CoMP::Container::SegmentedVector< T, N >::m_blocks.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector(), and UA_CoMP::Container::SegmentedVector< T, N >::operator=().
shrink_to_fit()
template<typename T , size_t N = 512> void UA_CoMP::Container::SegmentedVector< T, N >::shrink_to_fit () inline
Deallocates (empty) blocks to schrink capacity to fit current size.
Definition at line 220 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::size().
clear()
template<typename T , size_t N = 512> void UA_CoMP::Container::SegmentedVector< T, N >::clear () inline
Clears the content.
Definition at line 229 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::~SegmentedVector(), and UA_CoMP::Container::SegmentedVector< T, N >::operator=().
emplace_back()
template<typename T , size_t N = 512> template<class... Args> T * UA_CoMP::Container::SegmentedVector< T, N >::emplace_back (Args &&... args) inline
Constructs element in-place at the end.
Definition at line 243 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::get_chunk().
pop_back()
template<typename T , size_t N = 512> void UA_CoMP::Container::SegmentedVector< T, N >::pop_back () inline
Removes the last element.
Definition at line 250 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::at(), UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
push_back() [1/2]
template<typename T , size_t N = 512> T * UA_CoMP::Container::SegmentedVector< T, N >::push_back (const T & obj) inline
Adds element to end.
Definition at line 270 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::get_chunk().
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector(), and UA_CoMP::Container::SegmentedVector< T, N >::operator=().
push_back() [2/2]
template<typename T , size_t N = 512> T * UA_CoMP::Container::SegmentedVector< T, N >::push_back (T && obj) inline
Adds element to end.
Definition at line 277 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::get_chunk().
get_chunk()
template<typename T , size_t N = 512> T * UA_CoMP::Container::SegmentedVector< T, N >::get_chunk () inline private
Get next available chunk for element construction with placement new.
Definition at line 293 of file SegmentedVector.h.
References UA_CoMP::Container::SegmentedVector< T, N >::m_blocks, and UA_CoMP::Container::SegmentedVector< T, N >::m_size.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::emplace_back(), and UA_CoMP::Container::SegmentedVector< T, N >::push_back().
Friends And Related Function Documentation
SVIterator< T, N >
template<typename T , size_t N = 512> friend class SVIterator< T, N > friend
Definition at line 277 of file SegmentedVector.h.
SVIterator< T, N, T *, T &, false >
template<typename T , size_t N = 512> friend class SVIterator< T, N, T *, T &, false > friend
Definition at line 277 of file SegmentedVector.h.
Member Data Documentation
m_blocks
template<typename T , size_t N = 512> std::vector<Chunk*> UA_CoMP::Container::SegmentedVector< T, N >::m_blocks private
Vector registers pointers to blocks of chunks.
Definition at line 307 of file SegmentedVector.h.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector(), UA_CoMP::Container::SegmentedVector< T, N >::at(), UA_CoMP::Container::SegmentedVector< T, N >::back(), UA_CoMP::Container::SegmentedVector< T, N >::capacity(), UA_CoMP::Container::SegmentedVector< T, N >::clear(), UA_CoMP::Container::SegmentedVector< T, N >::get_block_count(), UA_CoMP::Container::SegmentedVector< T, N >::get_chunk(), UA_CoMP::Container::SegmentedVector< T, N >::operator=(), UA_CoMP::Container::SegmentedVector< T, N >::operator[](), UA_CoMP::Container::SegmentedVector< T, N >::pop_back(), UA_CoMP::Container::SegmentedVector< T, N >::reserve(), and UA_CoMP::Container::SegmentedVector< T, N >::shrink_to_fit().
m_size
template<typename T , size_t N = 512> size_t UA_CoMP::Container::SegmentedVector< T, N >::m_size private
Index of first free chunk when indexed contiguously.
Definition at line 308 of file SegmentedVector.h.
Referenced by UA_CoMP::Container::SegmentedVector< T, N >::SegmentedVector(), UA_CoMP::Container::SegmentedVector< T, N >::at(), UA_CoMP::Container::SegmentedVector< T, N >::back(), UA_CoMP::Container::SegmentedVector< T, N >::begin(), UA_CoMP::Container::SegmentedVector< T, N >::cbegin(), UA_CoMP::Container::SegmentedVector< T, N >::clear(), UA_CoMP::Container::SegmentedVector< T, N >::empty(), UA_CoMP::Container::SegmentedVector< T, N >::get_chunk(), UA_CoMP::Container::SegmentedVector< T, N >::operator=(), UA_CoMP::Container::SegmentedVector< T, N >::pop_back(), and UA_CoMP::Container::SegmentedVector< T, N >::size().
The documentation for this class was generated from the following file:
SegmentedVector.h