Gobelijn API documentation: Stack< std::string > Class Reference
Stack< std::string > Class Reference
Specialisation for string as element type.
#include <stack2.hpp>
Public Member Functions
Stack ()
Default constructor.
bool empty () const
Check whether stack is empty.
void pop ()
Pop element off the stack.
void push (const std::string &s)
Pushes element onto stack.
std::string top () const
Return top element of the stack (but not pop-ing it).
Private Attributes
std::deque< std::string > elems
Container for the stack elements.
Detailed Description
Specialisation for string as element type.
Definition at line 16 of file stack2.hpp.
Constructor & Destructor Documentation
Stack()
Stack< std::string >::Stack () inline
Default constructor.
Definition at line 20 of file stack2.hpp.
Member Function Documentation
empty()
bool Stack< std::string >::empty () const inline
Check whether stack is empty.
Returns
True iff empty.
Definition at line 24 of file stack2.hpp.
References Stack< T >::elems.
pop()
void Stack< std::string >::pop ()
Pop element off the stack.
Definition at line 43 of file stack2.hpp.
References Stack< T >::elems.
Referenced by main().
push()
void Stack< std::string >::push (const std::string & s)
Pushes element onto stack.
Parameters
s String pushed on stack.
Definition at line 51 of file stack2.hpp.
References Stack< T >::elems.
Referenced by main().
top()
std::string Stack< std::string >::top () const
Return top element of the stack (but not pop-ing it).
Returns
Top element of the stack.
Definition at line 53 of file stack2.hpp.
References Stack< T >::elems.
Referenced by main().
Member Data Documentation
elems
std::deque<std::string> Stack< std::string >::elems private
Container for the stack elements.
Definition at line 38 of file stack2.hpp.
The documentation for this class was generated from the following file:
stack2.hpp