Gobelijn API documentation: integral_demo.cpp File Reference
integral_demo.cpp File Reference
Demo for the Integral template.
#include "abs_diff.h"
#include "AGL_Quadrature.h"
#include "Integral.h"
#include "OscillatoryFunctor.h"
#include "PowerFunctor.h"
#include "SimpleRules.h"
#include <functional>
Functions
int main ()
Demo use of the Integral wrapper.
Detailed Description
Demo for the Integral template.
Author
Jan Broeckhove, CoMP/UA
Remarks
(c) Jan Broeckhove, 2011.
Definition in file integral_demo.cpp.
Function Documentation
main()
int main ()
Demo use of the Integral wrapper.
Definition at line 26 of file integral_demo.cpp.
References UA_CoMP::Num::abs_diff(), UA_CoMP::Num::OscillatoryFunctor::getIntegral(), and UA_CoMP::Num::make_integral().