Gobelijn API documentation: UA_CoMP::Misc::MemberTracer Class Reference
UA_CoMP::Misc::MemberTracer Class Reference
Class whose constructor/destructor pair are used to mark entering and leaving a member (function) body block.
#include <MemberTracer.h>
Public Member Functions
MemberTracer (const std::string &member_name, const void *object_this)
Constructor inserts message in TracerOutput about entering member body.
MemberTracer (const MemberTracer &)=delete
No copy constructor.
MemberTracer & operator= (const MemberTracer &)=delete
No assignment.
~MemberTracer ()
Destructor inserts message in TracerOutput about leaving member body.
Private Attributes
const std::string m_member_name
const void *const m_object_this
Detailed Description
Class whose constructor/destructor pair are used to mark entering and leaving a member (function) body block.
You do this by defining an automatic variable of MemberTracer at the beginning of the member body. The constructor triggers an appropriate message.The destructor for the variable gets called when leaving the member function body and triggers the appropriate message. The messages are logged to the tracer_log.
Definition at line 36 of file MemberTracer.h.
Constructor & Destructor Documentation
MemberTracer() [1/2]
UA_CoMP::Misc::MemberTracer::MemberTracer (const std::string & member_name, const void * object_this)
Constructor inserts message in TracerOutput about entering member body.
Definition at line 15 of file MemberTracer.cpp.
References UA_CoMP::Misc::g_tracer_log, UA_CoMP::Misc::TracerOutput::increase_indent(), UA_CoMP::Misc::TracerOutput::log(), m_member_name, and m_object_this.
MemberTracer() [2/2]
UA_CoMP::Misc::MemberTracer::MemberTracer (const MemberTracer &) delete
No copy constructor.
~MemberTracer()
UA_CoMP::Misc::MemberTracer::~MemberTracer ()
Destructor inserts message in TracerOutput about leaving member body.
Definition at line 24 of file MemberTracer.cpp.
References UA_CoMP::Misc::TracerOutput::decrease_indent(), UA_CoMP::Misc::g_tracer_log, UA_CoMP::Misc::TracerOutput::log(), m_member_name, and m_object_this.
Member Function Documentation
operator=()
MemberTracer& UA_CoMP::Misc::MemberTracer::operator= (const MemberTracer &) delete
No assignment.
Member Data Documentation
m_member_name
const std::string UA_CoMP::Misc::MemberTracer::m_member_name private
Definition at line 52 of file MemberTracer.h.
Referenced by MemberTracer(), and ~MemberTracer().
m_object_this
const void* const UA_CoMP::Misc::MemberTracer::m_object_this private
Definition at line 53 of file MemberTracer.h.
Referenced by MemberTracer(), and ~MemberTracer().
The documentation for this class was generated from the following files:
MemberTracer.h
MemberTracer.cpp