Gobelijn API documentation: tracing_example_exam::Room Class Reference
tracing_example_exam::Room Class Reference
#include <Room.h>
Public Member Functions
Room ()
Constructor.
Room (const Room &p)
Copy Constructor.
Room (Room &&p)
Move Constructor.
virtual ~Room ()
Destructor.
Room & operator= (const Room &)
Copy-assignment of a Room:
Room & operator= (Room &&)
Move-assignment of a Room:
virtual void info () const
Return room information.
Detailed Description
Definition at line 16 of file Room.h.
Constructor & Destructor Documentation
Room() [1/3]
tracing_example_exam::Room::Room ()
Constructor.
Definition at line 12 of file Room.cpp.
References COMP_MISC_MEMBER_TRACER.
Room() [2/3]
tracing_example_exam::Room::Room (const Room & p)
Copy Constructor.
Definition at line 14 of file Room.cpp.
References COMP_MISC_MEMBER_TRACER.
Room() [3/3]
tracing_example_exam::Room::Room (Room && p)
Move Constructor.
Definition at line 16 of file Room.cpp.
References COMP_MISC_MEMBER_TRACER.
~Room()
tracing_example_exam::Room::~Room () virtual
Destructor.
Definition at line 18 of file Room.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
Room & tracing_example_exam::Room::operator= (const Room &)
Copy-assignment of a Room:
Definition at line 20 of file Room.cpp.
References COMP_MISC_MEMBER_TRACER.
Referenced by tracing_example_exam::BathRoom::operator=(), tracing_example_exam::BedRoom::operator=(), and tracing_example_exam::Kitchen::operator=().
operator=() [2/2]
Room & tracing_example_exam::Room::operator= (Room &&)
Move-assignment of a Room:
Definition at line 26 of file Room.cpp.
References COMP_MISC_MEMBER_TRACER.
info()
void tracing_example_exam::Room::info () const virtual
Return room information.
Reimplemented in tracing_example_exam::BathRoom, tracing_example_exam::BedRoom, and tracing_example_exam::Kitchen.
Definition at line 32 of file Room.cpp.
References COMP_MISC_LOG_TRACER, and COMP_MISC_MEMBER_TRACER.
The documentation for this class was generated from the following files:
Room.h
Room.cpp