Gobelijn API documentation: app_example_exam_2021_2.cpp File Reference
app_example_exam_2021_2.cpp File Reference
Tracing exam, August 2021.
#include "objtracer/demobj.h"
#include "objtracer/demos.h"
#include "tracer/tracer.h"
#include <iostream>
#include <memory>
#include <stdexcept>
#include "HolidayHome.h"
#include "Building.h"
#include "Person.h"
Functions
int app_example_exam_2021_2 ()
Detailed Description
Tracing exam, August 2021.
Author
Thomas Avé (IDLab/UA)
Definition in file app_example_exam_2021_2.cpp.
Function Documentation
app_example_exam_2021_2()
int app_example_exam_2021_2 ()
Definition at line 44 of file app_example_exam_2021_2.cpp.
References COMP_MISC_BLOCK_TRACER, COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, tracing_example_exam::Building::getOwner(), tracing_example_exam::Building::info(), and tracing_example_exam::Rentable::rent().
Referenced by main().