Gobelijn API documentation: Polynomial< T > Class Template Reference
Polynomial< T > Class Template Reference
#include <polynomial.h>
Public Member Functions
Polynomial (const std::vector< T > &vect)
T operator() (const T &x)
Polynomial< T > operator+ (const Polynomial< T > &x) const
Polynomial< T > operator* (const Polynomial< T > &x) const
Polynomial< T > operator- (const Polynomial< T > &x) const
Polynomial< T > derive () const
T horner (const T &x) const
Protected Member Functions
Polynomial ()
Protected Attributes
std::vector< T > vect
Detailed Description
template<typename T>
class Polynomial< T >
Definition at line 8 of file polynomial.h.
Constructor & Destructor Documentation
Polynomial() [1/2]
template<typename T > Polynomial< T >::Polynomial (const std::vector< T > & vect) inline explicit
Definition at line 11 of file polynomial.h.
Polynomial() [2/2]
template<typename T > Polynomial< T >::Polynomial () inline protected
Definition at line 21 of file polynomial.h.
Member Function Documentation
operator()()
template<typename T > T Polynomial< T >::operator() (const T & x)
Definition at line 11 of file polynomial.cpp.
operator+()
template<typename T > Polynomial< T > Polynomial< T >::operator+ (const Polynomial< T > & x) const
Definition at line 23 of file polynomial.cpp.
References max(), and Polynomial< T >::vect.
operator*()
template<typename T > Polynomial< T > Polynomial< T >::operator* (const Polynomial< T > & x) const
Definition at line 33 of file polynomial.cpp.
References max(), and Polynomial< T >::vect.
operator-()
template<typename T > Polynomial< T > Polynomial< T >::operator- (const Polynomial< T > & x) const
Definition at line 43 of file polynomial.cpp.
References max(), and Polynomial< T >::vect.
derive()
template<typename T > Polynomial< T > Polynomial< T >::derive
Definition at line 53 of file polynomial.cpp.
References Polynomial< T >::vect.
horner()
template<typename T > T Polynomial< T >::horner (const T & x) const
Definition at line 63 of file polynomial.cpp.
Member Data Documentation
vect
template<typename T > std::vector<T> Polynomial< T >::vect protected
Definition at line 22 of file polynomial.h.
Referenced by Polynomial< T >::derive(), Polynomial< T >::operator*(), Polynomial< T >::operator+(), and Polynomial< T >::operator-().
The documentation for this class was generated from the following files:
polynomial.h
polynomial.cpp