Gobelijn API documentation: app_example_exam_2021_1.cpp File Reference
app_example_exam_2021_1.cpp File Reference
Example tracing exam.
#include "objtracer/demobj.h"
#include "objtracer/demos.h"
#include "tracer/tracer.h"
#include <iostream>
#include <stdexcept>
#include "HolidayHome.h"
#include "Person.h"
Functions
int app_example_exam_2021_1 ()
Detailed Description
Example tracing exam.
Author
Thomas Avé (IDLab/UA)
Definition in file app_example_exam_2021_1.cpp.
Function Documentation
app_example_exam_2021_1()
int app_example_exam_2021_1 ()
Definition at line 18 of file app_example_exam_2021_1.cpp.
References tracing_example_exam::Building::addNeighbour(), tracing_example_exam::HolidayHome::addNeighbour(), COMP_MISC_BLOCK_TRACER, COMP_MISC_FUNCTION_TRACER, COMP_MISC_LOG_TRACER, COMP_MISC_TRACER_OUTPUT_OFF, COMP_MISC_TRACER_OUTPUT_ON, tracing_example_exam::Building::info(), and tracing_example_exam::Rentable::rent().
Referenced by main().