Gobelijn API documentation: max1.hpp File Reference
max1.hpp File Reference
Template function returns maximum.
Functions
template<typename T >
T const & max (T const &a, T const &b)
Detailed Description
Template function returns maximum.
Author
J. Broeckhove - see copyright.txt
Definition in file max1.hpp.
Function Documentation
max()
template<typename T > T const& max (T const & a, T const & b) inline
Definition at line 9 of file max1.hpp.
Referenced by main(), Polynomial< T >::operator*(), Polynomial< T >::operator+(), and Polynomial< T >::operator-().