Gobelijn API documentation: Pimpl::MemoryPool Class Reference
Pimpl::MemoryPool Class Reference
A memory pool that uses the pointer-to-implementation idiom under the hood.
#include <MemoryPool.h>
Public Member Functions
MemoryPool ()=delete
MemoryPool (const MemoryPool &)=delete
MemoryPool (MemoryPool &&)=delete
MemoryPool & operator= (const MemoryPool &)=delete
MemoryPool & operator= (MemoryPool &&)=delete
MemoryPool (size_t capacity)
Creates a memory pool that can allocate at least as many bytes as specified by the given capacity.
~MemoryPool ()
Frees this memory pool's resources, if any.
template<typename T >
T * Allocate (size_t size=1)
Allocates a region of memory that is 'size * sizeof(T)' of bytes in size.
Private Member Functions
char * AllocateMemory (size_t size)
Allocates a region of memory that is the given number of bytes in size.
Private Attributes
std::unique_ptr< MemoryPoolImpl > m_impl
Fortunately, we don't need a definition to create a pointer to MemoryPoolImpl, so that's exactly what we'll do.
Detailed Description
A memory pool that uses the pointer-to-implementation idiom under the hood.
This allows developers to switch MemoryPool implementation without re-compiling any other files.
Definition at line 30 of file MemoryPool.h.
Constructor & Destructor Documentation
MemoryPool() [1/4]
Pimpl::MemoryPool::MemoryPool () delete
MemoryPool() [2/4]
Pimpl::MemoryPool::MemoryPool (const MemoryPool &) delete
MemoryPool() [3/4]
Pimpl::MemoryPool::MemoryPool (MemoryPool &&) delete
MemoryPool() [4/4]
Pimpl::MemoryPool::MemoryPool (size_t capacity)
Creates a memory pool that can allocate at least as many bytes as specified by the given capacity.
Creates a memory pool that has at least the given capacity.
Definition at line 36 of file array-impl.cpp.
~MemoryPool()
Pimpl::MemoryPool::~MemoryPool ()
Frees this memory pool's resources, if any.
Definition at line 41 of file array-impl.cpp.
References m_impl.
Member Function Documentation
operator=() [1/2]
MemoryPool& Pimpl::MemoryPool::operator= (const MemoryPool &) delete
operator=() [2/2]
MemoryPool& Pimpl::MemoryPool::operator= (MemoryPool &&) delete
Allocate()
template<typename T > T* Pimpl::MemoryPool::Allocate (size_t size = 1) inline
Allocates a region of memory that is 'size * sizeof(T)' of bytes in size.
It fits exactly 'size' instances of 'T'.
Definition at line 50 of file MemoryPool.h.
References AllocateMemory().
Referenced by main().
AllocateMemory()
char * Pimpl::MemoryPool::AllocateMemory (size_t size) private
Allocates a region of memory that is the given number of bytes in size.
Definition at line 51 of file array-impl.cpp.
References m_impl.
Referenced by Allocate().
Member Data Documentation
m_impl
std::unique_ptr<MemoryPoolImpl> Pimpl::MemoryPool::m_impl private
Fortunately, we don't need a definition to create a pointer to MemoryPoolImpl, so that's exactly what we'll do.
Definition at line 64 of file MemoryPool.h.
Referenced by ~MemoryPool(), and AllocateMemory().
The documentation for this class was generated from the following files:
MemoryPool.h
array-impl.cpp
malloc-impl.cpp