// The texts of the app, the same as the string resources of the Android app.

export const strings = {
  back: 'Back',
  listen: 'Listen',
  category: {
    Consonant: 'Consonant',
    Vowel: 'Vowel',
    ToneMark: 'Tone mark',
    Sign: 'Sign',
    Number: 'Number',
  },
  consonantClass: { Low: 'Low class', Mid: 'Mid class', High: 'High class' },
  startInOrder: 'In order',
  startShuffled: 'Shuffled',
  resume: 'Resume',
  newRound: 'New',

  homeTitle: 'Learn the Thai alphabet',
  homeFlashcardsTitle: 'Flashcards',
  homeFlashcardsDescription: 'Swipe through the letters at your own pace and listen to how each one is pronounced.',
  homeQuizTitle: 'Quiz',
  homeQuizDescription: 'Name each letter, or find the letter that matches a name. Letters you miss come back at the end until you get them right.',
  quizDirection: { LetterToName: 'Letter → name', NameToLetter: 'Name → letter' },
  filterHeading: 'Letters to practise',
  filterCategory: {
    Consonant: 'Consonants',
    Vowel: 'Vowels',
    ToneMark: 'Tone marks',
    Sign: 'Signs',
    Number: 'Numerals',
  },
  filterIncludeRare: 'Include rare letters',
  filterSummary: (selected, total) => `${selected} of ${total} letters`,
  filterSummaryAll: (total) => `All ${total} letters`,
  filterSummaryNone: 'No letters selected',
  filterModeCategories: 'Categories',
  filterModePick: 'Pick letters',
  filterPickedCount: (picked, total) => `${picked} of ${total} picked`,
  filterPickAll: 'Select all',
  filterPickNone: 'Clear',
  filterClass: { Low: 'Low', Mid: 'Mid', High: 'High' },
  nothingSelectedTitle: 'No letters selected',
  nothingSelectedMessage: 'Choose at least one letter to practise.',
  nothingSelectedChoose: 'Choose letters',
  cancel: 'Cancel',
  filterExpand: 'Show categories',
  filterCollapse: 'Hide categories',
  showTransliteration: 'Show transliteration',

  flashcardsTitle: 'Flashcards',
  flashcardsTitleShuffled: 'Shuffled flashcards',
  flashcardsPosition: (position, total) => `${position} / ${total}`,
  hideTransliterationAction: 'Hide transliteration',
  showTransliterationAction: 'Show transliteration',
  tapToReveal: 'Tap to reveal',
  previous: 'Previous',
  next: 'Next',
  done: 'Done',

  quizTitle: { LetterToName: 'Name the letter', NameToLetter: 'Find the letter' },
  quizProgress: (learned, total) => `${learned} of ${total} learned`,
  quizToRepeat: (count) => `${count} to repeat`,
  quizPrompt: 'What is this letter?',
  quizRepeatBadge: 'Try again',
  quizShowAnswer: 'Show answer',
  quizDidYouGetIt: 'Did you get it right?',
  quizWrong: 'Wrong',
  quizRight: 'Right',
  findPrompt: 'Which letter is this?',
  findHint: 'Pick the matching letter',
  findCorrect: 'Correct!',
  findWrong: 'Not quite',
  findChoiceCorrect: 'Correct letter',
  findChoiceWrong: 'Your pick',

  resultsTitle: 'Quiz complete',
  resultsScore: (correct, total) => `${correct} of ${total} right on the first try`,
  resultsPerfect: 'A perfect run. Every letter was right the first time!',
  resultsMissedHeading: 'Letters to keep practising',
  resultsMissCount: (count) => `×${count}`,
  resultsNewQuiz: 'New quiz',
  resultsHome: 'Back to home',
};
