Object Tracer: src/exercises/app_exception.cpp File Reference
app_exception.cpp File Reference
#include "utils/tracer.h"
#include "vehicles/Bicycle.h"
#include "vehicles/Exception.h"
#include "vehicles/SailBoat.h"
#include <iostream>
Functions
int app_exception ()
Function Documentation
app_exception()
int app_exception ()
Demo prog for ctor/dtor features in class derivation.
Returns
status
Exceptions
None.
Definition at line 15 of file app_exception.cpp.
                    {
    FUNCTION_TRACER;
    try {
        BLOCK_TRACER("Try block");
        LOG_TRACER(" statement: Bicycle m1(\"Honda\", \"red\");");
        Bicycle m1("Honda", "red");
        LOG_TRACER(" statement: m1.get_nfo();");
        m1.info();
        LOG_TRACER(" statement: SailBoat s1(\"Marina\");");
        SailBoat s1("Marina");
        ;
        vector<double> direction(2);
        direction[0] = 1.0;
        direction[1] = -1.0;
        LOG_TRACER(" statement: s1.move(4, direction);");
        s1.move(4, direction);
        if (direction[0] == 1.0) {
            throw SailingException("Help");
        }
        LOG_TRACER(" statement: s1.startSinking();");
        s1.start_sinking();
        LOG_TRACER(" statement: s1.displayInfo();");
        s1.info();
    } catch (LoadingException& e) {
        LOG_TRACER(" catch clause with LoadingException");
        e.info();
    } catch (SailingException& e) {
        LOG_TRACER(" catch clause with SailingException");
        e.info();
    } catch (Exception& e) {
        LOG_TRACER(" catch clause with Exception");
        e.info();
        LOG_TRACER(e.what());
    }
    LOG_TRACER(" statement: return 0;");
    return 0;
}
References BLOCK_TRACER, FUNCTION_TRACER, Vehicles::Bicycle::info(), Vehicles::LoadingException::info(), Vehicles::SailBoat::info(), LOG_TRACER, Vehicles::SailBoat::move(), Vehicles::WaterVehicle::start_sinking(), and Vehicles::Exception::what().
Referenced by main().