Object Tracer: Vehicles::WaterVehicle Class Reference
Vehicles::WaterVehicle Class Reference abstract
#include <WaterVehicle.h>
Public Member Functions
WaterVehicle ()
Default constructor.
WaterVehicle (const WaterVehicle &ori)
Copy constructor.
WaterVehicle (WaterVehicle &&ori) noexcept
Move constructor.
WaterVehicle & operator= (const WaterVehicle &rhs)
Copy assignment.
WaterVehicle & operator= (WaterVehicle &&rhs) noexcept
Move assignment.
~WaterVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override=0
Pure virtual method for motion.
void start_sinking ()
Start sinking, even if you are already sinking.
void stop_sinking ()
Stop sinking, even if you were not sinking in the first place.
Public Member Functions inherited from Vehicles::Vehicle
virtual ~Vehicle ()=default
Destructor.
virtual void info () const =0
Return vehicle information.
virtual void move (double speed, std::vector< double > direction)=0
Motion of vehicle.
Private Attributes
bool m_sinking
Detailed Description
Abstract WaterVehicle class.
Definition at line 10 of file WaterVehicle.h.
Constructor & Destructor Documentation
WaterVehicle() [1/3]
Vehicles::WaterVehicle::WaterVehicle ()
Default constructor.
Definition at line 8 of file WaterVehicle.cpp.
: Vehicle(), m_sinking(false) { MEMBER_TRACER; }
References MEMBER_TRACER.
WaterVehicle() [2/3]
Vehicles::WaterVehicle::WaterVehicle (const WaterVehicle & ori)
Copy constructor.
Definition at line 10 of file WaterVehicle.cpp.
: Vehicle(ori), m_sinking(ori.m_sinking) { MEMBER_TRACER; }
References MEMBER_TRACER.
WaterVehicle() [3/3]
Vehicles::WaterVehicle::WaterVehicle (WaterVehicle && ori) noexcept
Move constructor.
Definition at line 12 of file WaterVehicle.cpp.
: Vehicle(ori), m_sinking(ori.m_sinking) { MEMBER_TRACER; }
References MEMBER_TRACER.
~WaterVehicle()
Vehicles::WaterVehicle::~WaterVehicle () override
Destructor.
Definition at line 32 of file WaterVehicle.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
info()
void Vehicles::WaterVehicle::info () const override virtual
Return identification info.
Implements Vehicles::Vehicle.
Definition at line 34 of file WaterVehicle.cpp.
{
    MEMBER_TRACER;
    string s{"I'm a generic Water vehicle"};
    if (m_sinking) {
        s.append(" and I'm sinking!");
    }
    LOG_TRACER(s);
}
References LOG_TRACER, m_sinking, and MEMBER_TRACER.
move()
void Vehicles::WaterVehicle::move (double speed, std::vector< double > direction) override pure virtual
Pure virtual method for motion.
Implements Vehicles::Vehicle.
Implemented in Vehicles::SailBoat.
operator=() [1/2]
WaterVehicle & Vehicles::WaterVehicle::operator= (const WaterVehicle & rhs)
Copy assignment.
Definition at line 14 of file WaterVehicle.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        Vehicle::operator=(rhs);
        m_sinking = rhs.m_sinking;
    }
    return *this;
}
References m_sinking, and MEMBER_TRACER.
Referenced by Vehicles::SailBoat::operator=().
operator=() [2/2]
WaterVehicle & Vehicles::WaterVehicle::operator= (WaterVehicle && rhs) noexcept
Move assignment.
Definition at line 23 of file WaterVehicle.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        Vehicle::operator=(rhs);
        m_sinking = rhs.m_sinking;
    }
    return *this;
}
References MEMBER_TRACER.
start_sinking()
void Vehicles::WaterVehicle::start_sinking ()
Start sinking, even if you are already sinking.
Definition at line 43 of file WaterVehicle.cpp.
{
    MEMBER_TRACER;
    m_sinking = true;
}
References m_sinking, and MEMBER_TRACER.
Referenced by app_exception(), and app_hierarchies().
stop_sinking()
void Vehicles::WaterVehicle::stop_sinking ()
Stop sinking, even if you were not sinking in the first place.
Definition at line 48 of file WaterVehicle.cpp.
{
    MEMBER_TRACER;
    m_sinking = false;
}
References m_sinking, and MEMBER_TRACER.
Member Data Documentation
m_sinking
bool Vehicles::WaterVehicle::m_sinking private
Definition at line 43 of file WaterVehicle.h.
Referenced by info(), operator=(), start_sinking(), and stop_sinking().
The documentation for this class was generated from the following files:
src/vehicles/WaterVehicle.h
src/vehicles/WaterVehicle.cpp