Object Tracer: tracing_exam_2022_1::Visitor Class Reference
tracing_exam_2022_1::Visitor Class Reference
#include <Visitor.h>
Public Member Functions
Visitor ()
Constructor.
template<typename T >
void visit (T *t)
template<>
void visit (HolidayHome *h)
template<>
void visit (HolidayHome *h)
template<>
void visit (HolidayHome *h)
Detailed Description
Definition at line 20 of file Visitor.h.
Constructor & Destructor Documentation
Visitor()
tracing_exam_2022_1::Visitor::Visitor ()
Constructor.
Definition at line 13 of file Visitor.cpp.
                 {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
Member Function Documentation
visit() [1/4]
template<> void tracing_exam_2022_1::Visitor::visit (HolidayHome * h)
Definition at line 18 of file Visitor.cpp.
{
    MEMBER_TRACER;
    LOG_TRACER("Visiting a " + h->getName());
    h->rent(Person("The Visitor"));
}
References tracing_exam_2022_1::HolidayHome::getName(), LOG_TRACER, MEMBER_TRACER, and tracing_exam_2022_1::Rentable::rent().
visit() [2/4]
template<> void tracing_exam_2022_1::Visitor::visit (HolidayHome * h)
Definition at line 22 of file Visitor.cpp.
{
    MEMBER_TRACER;
    LOG_TRACER("Visiting a " + h->getName());
    h->rent(Person("The Visitor"));
}
References tracing_exam_2022_1::HolidayHome::getName(), LOG_TRACER, MEMBER_TRACER, and tracing_exam_2022_1::Rentable::rent().
visit() [3/4]
template<> void tracing_exam_2022_1::Visitor::visit (HolidayHome * h)
visit() [4/4]
template<typename T > void tracing_exam_2022_1::Visitor::visit (T * t) inline
Visit the provided object Make sure you provide the actual type T for each template instantiation For example: —> function body: void tracing_exam_2022_1::Visitor::visit(T*) [with T = tracing_exam_2022_1::Building]
Definition at line 30 of file Visitor.h.
{
            MEMBER_TRACER;
            LOG_TRACER("Visiting a " + t->getName());
        }
References LOG_TRACER, and MEMBER_TRACER.
Referenced by tracing_exam_2022_1::Building::welcome(), tracing_exam_2022_1::HolidayHome::welcome(), and tracing_exam_2022_1::House::welcome().
The documentation for this class was generated from the following files:
src/exams/2022_1/Visitor.h
src/exams/2022_1/Visitor.cpp
src/exams/2022_2/Visitor.cpp
src/exams/2022_2/Visitor.h