Object Tracer: tracing_exam_2021::Building Class Reference
tracing_exam_2021::Building Class Reference
#include <Building.h>
Public Member Functions
Building (Person &owner)
Constructor.
Building (const Person &owner)
Constructor.
Building (Person &&owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual std::string getName () const
Returns the name of the Building.
virtual Person & getOwner ()
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
Protected Attributes
std::vector< std::shared_ptr< const Room > > m_rooms
std::vector< Building * > m_neighbours
Person m_owner
Detailed Description
Definition at line 19 of file Building.h.
Constructor & Destructor Documentation
Building() [1/5]
tracing_exam_2021::Building::Building (Person & owner)
Constructor.
Definition at line 15 of file Building.cpp.
: m_rooms(), m_neighbours(), m_owner(owner) { MEMBER_TRACER; }
References MEMBER_TRACER.
Building() [2/5]
tracing_exam_2021::Building::Building (const Person & owner)
Constructor.
Definition at line 17 of file Building.cpp.
: m_rooms(), m_neighbours(), m_owner(owner) { MEMBER_TRACER; }
References MEMBER_TRACER.
Building() [3/5]
tracing_exam_2021::Building::Building (Person && owner)
Constructor.
Definition at line 19 of file Building.cpp.
: m_rooms(), m_neighbours(), m_owner(std::move(owner)) { MEMBER_TRACER; }
References MEMBER_TRACER.
Building() [4/5]
tracing_exam_2021::Building::Building (const Building & b)
Copy Constructor.
Definition at line 21 of file Building.cpp.
                                    : m_rooms(), m_neighbours(), m_owner(b.m_owner) {
    MEMBER_TRACER;
    m_rooms = b.m_rooms;
}
References m_rooms, and MEMBER_TRACER.
Building() [5/5]
tracing_exam_2021::Building::Building (Building && b)
Move Constructor.
Definition at line 26 of file Building.cpp.
                               : m_rooms(), m_neighbours(), m_owner(std::move(b.m_owner)) {
    MEMBER_TRACER;
    m_rooms.clear();
    m_neighbours.clear();
    m_rooms = std::move(b.m_rooms);
    m_neighbours = std::move(b.m_neighbours);
}
References m_neighbours, m_rooms, and MEMBER_TRACER.
~Building()
tracing_exam_2021::Building::~Building () virtual
Destructor.
Definition at line 34 of file Building.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
addNeighbour()
void tracing_exam_2021::Building::addNeighbour (Building * neighbour) virtual
Adds a Building to the list of neighbours of the current building It does not take ownership of this neighbouring Building
Definition at line 77 of file Building.cpp.
{
    MEMBER_TRACER;
    if (neighbour != this) {
        m_neighbours.emplace_back(neighbour);
    }
}
References m_neighbours, and MEMBER_TRACER.
Referenced by app_exam_2021_1().
getName()
std::string tracing_exam_2021::Building::getName () const virtual
Returns the name of the Building.
Reimplemented in tracing_exam_2021::HolidayHome, and tracing_exam_2021::House.
Definition at line 67 of file Building.cpp.
{
    MEMBER_TRACER;
    return "Generic Building";
}
References MEMBER_TRACER.
Referenced by info().
getOwner()
Person & tracing_exam_2021::Building::getOwner () virtual
Returns the Person who owns the building.
Definition at line 72 of file Building.cpp.
{
    MEMBER_TRACER;
    return m_owner;
}
References m_owner, and MEMBER_TRACER.
Referenced by app_exam_2021_2().
info()
void tracing_exam_2021::Building::info () const virtual
Prints building information.
Definition at line 58 of file Building.cpp.
{
    MEMBER_TRACER;
    LOG_TRACER(getName() + " containing " + std::to_string(m_rooms.size()) + " rooms:");
    for (auto room : m_rooms) {
        room->info();
    }
    LOG_TRACER("And " + std::to_string(m_neighbours.size()) + " neighbours");
}
References getName(), LOG_TRACER, m_neighbours, m_rooms, and MEMBER_TRACER.
Referenced by app_exam_2021_1(), and app_exam_2021_2().
operator=() [1/2]
Building & tracing_exam_2021::Building::operator= (Building && other)
Move-assignment of a Building:
Definition at line 46 of file Building.cpp.
{
    MEMBER_TRACER;
    if (this != &other) {
        m_rooms.clear();
        m_neighbours.clear();
        m_neighbours = std::move(other.m_neighbours);
        m_rooms = std::move(other.m_rooms);
        m_owner = std::move(other.m_owner);
    }
    return *this;
}
References m_neighbours, m_owner, m_rooms, and MEMBER_TRACER.
operator=() [2/2]
Building & tracing_exam_2021::Building::operator= (const Building & other)
Copy-assignment of a Building:
Definition at line 36 of file Building.cpp.
{
    MEMBER_TRACER;
    if (this != &other) {
        m_rooms = other.m_rooms;
        m_neighbours = other.m_neighbours;
        m_owner = Person(other.m_owner);
    }
    return *this;
}
References m_neighbours, m_owner, m_rooms, and MEMBER_TRACER.
Referenced by tracing_exam_2021::House::operator=().
Member Data Documentation
m_neighbours
std::vector<Building*> tracing_exam_2021::Building::m_neighbours protected
Definition at line 60 of file Building.h.
Referenced by addNeighbour(), tracing_exam_2021::HolidayHome::addNeighbour(), tracing_exam_2021::House::addNeighbour(), Building(), info(), and operator=().
m_owner
Person tracing_exam_2021::Building::m_owner protected
Definition at line 61 of file Building.h.
Referenced by getOwner(), and operator=().
m_rooms
std::vector<std::shared_ptr<const Room> > tracing_exam_2021::Building::m_rooms protected
Definition at line 59 of file Building.h.
Referenced by Building(), tracing_exam_2021::House::House(), info(), and operator=().
The documentation for this class was generated from the following files:
src/exams/2021/Building.h
src/exams/2021/Building.cpp