Object Tracer: Utils::MemberTracer Class Reference
Utils::MemberTracer Class Reference
#include <MemberTracer.h>
Public Member Functions
MemberTracer (const std::string &member_name, const void *object_this)
Constructor inserts message in TracerOutput about entering member body.
MemberTracer (const MemberTracer &)=delete
No copy constructor.
MemberTracer & operator= (const MemberTracer &)=delete
No assignment.
~MemberTracer ()
Destructor inserts message in TracerOutput about leaving member body.
Private Attributes
const std::string m_member_name
const void *const m_object_this
Detailed Description
Class whose constructor/destructor pair are used to mark entering and leaving a member (function) body block. You do this by defining an automatic variable of MemberTracer at the beginning of the member body. The constructor triggers an appropriate message.The destructor for the variable gets called when leaving the member function body and triggers the appropriate message. The messages are logged to the tracer_log.
Definition at line 29 of file MemberTracer.h.
Constructor & Destructor Documentation
MemberTracer() [1/2]
MemberTracer::MemberTracer (const std::string & member_name, const void * object_this)
Constructor inserts message in TracerOutput about entering member body.
Definition at line 6 of file MemberTracer.cpp.
    : m_member_name(member_name), m_object_this(object_this) {
    std::ostringstream ss;
    ss << "---> member for object: " << m_object_this << " : " << m_member_name;
    TracerOutput::getInstance().log(ss.str());
    TracerOutput::getInstance().increase_indent();
}
References Utils::TracerOutput::getInstance(), Utils::TracerOutput::increase_indent(), Utils::TracerOutput::log(), m_member_name, and m_object_this.
MemberTracer() [2/2]
Utils::MemberTracer::MemberTracer (const MemberTracer &) delete
No copy constructor.
~MemberTracer()
MemberTracer::~MemberTracer ()
Destructor inserts message in TracerOutput about leaving member body.
Definition at line 14 of file MemberTracer.cpp.
{
    TracerOutput::getInstance().decrease_indent();
    std::ostringstream ss;
    ss << "<--- member for object: " << m_object_this << " : " << m_member_name;
    TracerOutput::getInstance().log(ss.str());
}
References Utils::TracerOutput::decrease_indent(), Utils::TracerOutput::getInstance(), Utils::TracerOutput::log(), m_member_name, and m_object_this.
Member Function Documentation
operator=()
MemberTracer & Utils::MemberTracer::operator= (const MemberTracer &) delete
No assignment.
Member Data Documentation
m_member_name
const std::string Utils::MemberTracer::m_member_name private
Definition at line 44 of file MemberTracer.h.
Referenced by MemberTracer(), and ~MemberTracer().
m_object_this
const void* const Utils::MemberTracer::m_object_this private
Definition at line 45 of file MemberTracer.h.
Referenced by MemberTracer(), and ~MemberTracer().
The documentation for this class was generated from the following files:
src/utils/MemberTracer.h
src/utils/MemberTracer.cpp