Object Tracer: Vehicles::SailBoat Class Reference
Vehicles::SailBoat Class Reference
#include <SailBoat.h>
Public Member Functions
SailBoat (std::string name)
Parametrized constructor initializes the name of the boat.
SailBoat (const SailBoat &ori)
Copy constructor.
SailBoat (SailBoat &&ori) noexcept
Move constructor.
SailBoat & operator= (const SailBoat &rhs)
Copy assignment.
SailBoat & operator= (SailBoat &&rhs) noexcept
Move assignment.
~SailBoat () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Sailboat motion.
Public Member Functions inherited from Vehicles::WaterVehicle
WaterVehicle ()
Default constructor.
WaterVehicle (const WaterVehicle &ori)
Copy constructor.
WaterVehicle (WaterVehicle &&ori) noexcept
Move constructor.
WaterVehicle & operator= (const WaterVehicle &rhs)
Copy assignment.
WaterVehicle & operator= (WaterVehicle &&rhs) noexcept
Move assignment.
~WaterVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override=0
Pure virtual method for motion.
void start_sinking ()
Start sinking, even if you are already sinking.
void stop_sinking ()
Stop sinking, even if you were not sinking in the first place.
Public Member Functions inherited from Vehicles::Vehicle
virtual ~Vehicle ()=default
Destructor.
virtual void info () const =0
Return vehicle information.
virtual void move (double speed, std::vector< double > direction)=0
Motion of vehicle.
Private Attributes
std::string m_name
bool m_sails_up
Detailed Description
A simple SailBoat class.
Definition at line 10 of file SailBoat.h.
Constructor & Destructor Documentation
SailBoat() [1/3]
Vehicles::SailBoat::SailBoat (std::string name) explicit
Parametrized constructor initializes the name of the boat.
Definition at line 6 of file SailBoat.cpp.
: WaterVehicle(), m_name(std::move(name)), m_sails_up(false) { MEMBER_TRACER; }
References MEMBER_TRACER.
SailBoat() [2/3]
Vehicles::SailBoat::SailBoat (const SailBoat & ori)
Copy constructor.
Definition at line 8 of file SailBoat.cpp.
                                      : WaterVehicle(ori), m_name(ori.m_name), m_sails_up(ori.m_sails_up) {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
SailBoat() [3/3]
Vehicles::SailBoat::SailBoat (SailBoat && ori) noexcept
Move constructor.
Definition at line 12 of file SailBoat.cpp.
    : WaterVehicle(std::move(ori)), m_name(std::move(ori.m_name)), m_sails_up(ori.m_sails_up) {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
~SailBoat()
Vehicles::SailBoat::~SailBoat () override
Destructor.
Definition at line 37 of file SailBoat.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
info()
void Vehicles::SailBoat::info () const override virtual
Return identification info.
Implements Vehicles::Vehicle.
Definition at line 39 of file SailBoat.cpp.
{
    MEMBER_TRACER;
    std::string s{"I'm a sailboat named \"" + m_name + "\" and my sails are "};
    if (m_sails_up) {
        s.append("up.");
    } else {
        s.append("down.");
    }
    LOG_TRACER(s);
}
References LOG_TRACER, m_name, m_sails_up, and MEMBER_TRACER.
Referenced by app_exception(), and app_hierarchies().
move()
void Vehicles::SailBoat::move (double speed, std::vector< double > direction) override virtual
Sailboat motion.
Implements Vehicles::WaterVehicle.
Definition at line 50 of file SailBoat.cpp.
{
    MEMBER_TRACER;
    m_sails_up = true;
}
References m_sails_up, and MEMBER_TRACER.
Referenced by app_exception(), and app_hierarchies().
operator=() [1/2]
SailBoat & Vehicles::SailBoat::operator= (const SailBoat & rhs)
Copy assignment.
Definition at line 17 of file SailBoat.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        WaterVehicle::operator=(rhs);
        m_name = rhs.m_name;
        m_sails_up = rhs.m_sails_up;
    }
    return *this;
}
References m_name, m_sails_up, MEMBER_TRACER, and Vehicles::WaterVehicle::operator=().
operator=() [2/2]
SailBoat & Vehicles::SailBoat::operator= (SailBoat && rhs) noexcept
Move assignment.
Definition at line 27 of file SailBoat.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        WaterVehicle::operator=(rhs);
        m_name = std::move(rhs.m_name);
        m_sails_up = rhs.m_sails_up;
    }
    return *this;
}
References MEMBER_TRACER, and Vehicles::WaterVehicle::operator=().
Member Data Documentation
m_name
std::string Vehicles::SailBoat::m_name private
Definition at line 37 of file SailBoat.h.
Referenced by info(), and operator=().
m_sails_up
bool Vehicles::SailBoat::m_sails_up private
Definition at line 38 of file SailBoat.h.
Referenced by info(), move(), and operator=().
The documentation for this class was generated from the following files:
src/vehicles/SailBoat.h
src/vehicles/SailBoat.cpp