Object Tracer: tracing_exam_2023_1::Subject< T > Class Template Reference
tracing_exam_2023_1::Subject< T > Class Template Reference
#include <Subject.h>
Public Member Functions
Subject ()
virtual ~Subject ()
void attach (std::shared_ptr< Observer< T > > observer, Event e)
void notify (Event e)
Private Attributes
std::map< Event, std::vector< std::shared_ptr< Observer< T > > > > m_observers
Detailed Description
template<typename T>
class tracing_exam_2023_1::Subject< T >
Definition at line 20 of file Subject.h.
Constructor & Destructor Documentation
Subject()
template<typename T > tracing_exam_2023_1::Subject< T >::Subject () inline
Definition at line 23 of file Subject.h.
                     : m_observers() {
                MEMBER_TRACER;
            }
References MEMBER_TRACER.
~Subject()
template<typename T > virtual tracing_exam_2023_1::Subject< T >::~Subject () inline virtual
Definition at line 26 of file Subject.h.
{
                MEMBER_TRACER;
            }
References MEMBER_TRACER.
Member Function Documentation
attach()
template<typename T > void tracing_exam_2023_1::Subject< T >::attach (std::shared_ptr< Observer< T > > observer, Event e) inline
Definition at line 29 of file Subject.h.
            {
                MEMBER_TRACER;
                m_observers[e].push_back(observer);
            }
References tracing_exam_2023_1::Subject< T >::m_observers, and MEMBER_TRACER.
Referenced by tracing_exam_2023_1::RentableObserver::attach(), and tracing_exam_2023_1::RoadObserver::attach().
notify()
template<typename T > void tracing_exam_2023_1::Subject< T >::notify (Event e) inline
Definition at line 34 of file Subject.h.
            {
                MEMBER_TRACER;
                for (auto o: m_observers[e])
                    o->update(static_cast<T *>(this), e);
            }
References tracing_exam_2023_1::Subject< T >::m_observers, and MEMBER_TRACER.
Referenced by tracing_exam_2023_1::Road::addBuilding(), tracing_exam_2023_1::Road::removeBuilding(), and tracing_exam_2023_1::Rentable::rent().
Member Data Documentation
m_observers
template<typename T > std::map<Event, std::vector<std::shared_ptr<Observer<T> > > > tracing_exam_2023_1::Subject< T >::m_observers private
Definition at line 41 of file Subject.h.
Referenced by tracing_exam_2023_1::Subject< T >::attach(), and tracing_exam_2023_1::Subject< T >::notify().
The documentation for this class was generated from the following file:
src/exams/2023_1/Subject.h