Object Tracer: tracing_exam_2022_2::Road Class Reference
tracing_exam_2022_2::Road Class Reference
#include <Road.h>
Public Member Functions
Road ()
Constructor.
Road (const Road &r)
Copy Constructor.
Road (Road &&r)
Move Constructor.
virtual ~Road ()
Destructor.
Road & operator= (const Road &)
Copy-assignment of a Road:
Road & operator= (Road &&)
Move-assignment of a Road:
void addBuilding (std::unique_ptr< Building > b, unsigned int number)
Add a Building to this Road at the given number.
void removeBuilding (unsigned int number)
Remove the Building with the given number from this Road.
Building & getBuilding (unsigned int number)
Retrieve the Building with the given number from this Road.
bool hasBuilding (int number) const
Returns whether or not this Road contains a Building at the given number.
void welcome (Visitor &v)
Welcome the Visitor to all Buildings in this Road.
Public Member Functions inherited from tracing_exam_2022_2::Subject< Road >
Subject ()
virtual ~Subject ()
void attach (std::shared_ptr< Observer< Road > > observer, Event e)
void notify (Event e)
Private Attributes
std::map< unsigned int, std::unique_ptr< Building > > m_buildings
Detailed Description
Definition at line 21 of file Road.h.
Constructor & Destructor Documentation
Road() [1/3]
tracing_exam_2022_2::Road::Road ()
Constructor.
Definition at line 15 of file Road.cpp.
: m_buildings() { MEMBER_TRACER; }
References MEMBER_TRACER.
Road() [2/3]
tracing_exam_2022_2::Road::Road (const Road & r)
Copy Constructor.
Definition at line 19 of file Road.cpp.
                           : m_buildings() {
    MEMBER_TRACER;
    for (auto const& [key, val]: other.m_buildings) {
        m_buildings[key] = std::make_unique<Building>(*val);
    }
}
References m_buildings, and MEMBER_TRACER.
Road() [3/3]
tracing_exam_2022_2::Road::Road (Road && r)
Move Constructor.
Definition at line 26 of file Road.cpp.
: m_buildings(std::move(other.m_buildings)) { MEMBER_TRACER; }
References MEMBER_TRACER.
~Road()
tracing_exam_2022_2::Road::~Road () virtual
Destructor.
Definition at line 17 of file Road.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
addBuilding()
void tracing_exam_2022_2::Road::addBuilding (std::unique_ptr< Building > b, unsigned int number)
Add a Building to this Road at the given number.
Definition at line 49 of file Road.cpp.
{
    MEMBER_TRACER;
    if (hasBuilding(number)) {
        throw std::runtime_error("A Building already exists at this number!");
    }
    for (int a: {-1, 1}){
        int neighbour_number = number + (a*2);
        if (hasBuilding(neighbour_number)) {
            m_buildings.at(neighbour_number)->addNeighbour(b.get());
            b->addNeighbour(m_buildings.at(neighbour_number).get());
        }
    }
    m_buildings.insert(std::make_pair(number, std::move(b)));
    notify(Event::BuildingAdded);
}
References tracing_exam_2022_2::BuildingAdded, hasBuilding(), m_buildings, MEMBER_TRACER, and tracing_exam_2022_2::Subject< Road >::notify().
Referenced by app_exam_2022_2().
getBuilding()
Building & tracing_exam_2022_2::Road::getBuilding (unsigned int number)
Retrieve the Building with the given number from this Road.
Definition at line 74 of file Road.cpp.
{
    MEMBER_TRACER;
    if (!hasBuilding(number)) {
        throw std::runtime_error("This Road does not contain a Building at the given number!");
    }
    return *m_buildings.at(number);
}
References hasBuilding(), m_buildings, and MEMBER_TRACER.
Referenced by app_exam_2022_2().
hasBuilding()
bool tracing_exam_2022_2::Road::hasBuilding (int number) const
Returns whether or not this Road contains a Building at the given number.
Definition at line 82 of file Road.cpp.
{
    MEMBER_TRACER;
    return m_buildings.count(number);
}
References m_buildings, and MEMBER_TRACER.
Referenced by addBuilding(), getBuilding(), and removeBuilding().
operator=() [1/2]
Road & tracing_exam_2022_2::Road::operator= (const Road & other)
Copy-assignment of a Road:
Definition at line 28 of file Road.cpp.
{
    MEMBER_TRACER;
    if (this != &other) {
        m_buildings.clear();
        for (auto const& [key, val]: other.m_buildings) {
            m_buildings[key] = std::make_unique<Building>(*val);
        }
    }
    return *this;
}
References m_buildings, and MEMBER_TRACER.
operator=() [2/2]
Road & tracing_exam_2022_2::Road::operator= (Road && other)
Move-assignment of a Road:
Definition at line 40 of file Road.cpp.
{
    MEMBER_TRACER;
    if (this != &other) {
        m_buildings = std::move(other.m_buildings);
    }
    return *this;
}
References m_buildings, and MEMBER_TRACER.
removeBuilding()
void tracing_exam_2022_2::Road::removeBuilding (unsigned int number)
Remove the Building with the given number from this Road.
Definition at line 65 of file Road.cpp.
{
    MEMBER_TRACER;
    if (!hasBuilding(number)) {
        throw std::runtime_error("This Road does not contain a Building at the given number!");
    }
    m_buildings.erase(number);
    notify(Event::BuildingRemoved);
}
References tracing_exam_2022_2::BuildingRemoved, hasBuilding(), m_buildings, MEMBER_TRACER, and tracing_exam_2022_2::Subject< Road >::notify().
welcome()
void tracing_exam_2022_2::Road::welcome (Visitor & v)
Welcome the Visitor to all Buildings in this Road.
Definition at line 87 of file Road.cpp.
{
    MEMBER_TRACER;
    for (auto const& [key, val]: m_buildings) {
        val->welcome(v);
    }
}
References m_buildings, and MEMBER_TRACER.
Referenced by app_exam_2022_2().
Member Data Documentation
m_buildings
std::map<unsigned int, std::unique_ptr<Building> > tracing_exam_2022_2::Road::m_buildings private
Definition at line 58 of file Road.h.
Referenced by addBuilding(), getBuilding(), hasBuilding(), operator=(), removeBuilding(), Road(), and welcome().
The documentation for this class was generated from the following files:
src/exams/2022_2/Road.h
src/exams/2022_2/Road.cpp