Object Tracer: tracing_exam_2022_2::Room Class Reference
tracing_exam_2022_2::Room Class Reference
#include <Room.h>
Public Member Functions
Room ()
Constructor.
Room (const Room &p)
Copy Constructor.
Room (Room &&p)
Move Constructor.
virtual ~Room ()
Destructor.
Room & operator= (const Room &)
Copy-assignment of a Room:
Room & operator= (Room &&)
Move-assignment of a Room:
virtual void info () const
Return room information.
Detailed Description
Definition at line 16 of file Room.h.
Constructor & Destructor Documentation
Room() [1/3]
tracing_exam_2022_2::Room::Room ()
Constructor.
Definition at line 12 of file Room.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Room() [2/3]
tracing_exam_2022_2::Room::Room (const Room & p)
Copy Constructor.
Definition at line 14 of file Room.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Room() [3/3]
tracing_exam_2022_2::Room::Room (Room && p)
Move Constructor.
Definition at line 16 of file Room.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
~Room()
tracing_exam_2022_2::Room::~Room () virtual
Destructor.
Definition at line 18 of file Room.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
info()
void tracing_exam_2022_2::Room::info () const virtual
Return room information.
Reimplemented in tracing_exam_2022_2::BathRoom, tracing_exam_2022_2::BedRoom, and tracing_exam_2022_2::Kitchen.
Definition at line 32 of file Room.cpp.
{
        MEMBER_TRACER;
        LOG_TRACER("Generic Room");
}
References LOG_TRACER, and MEMBER_TRACER.
operator=() [1/2]
Room & tracing_exam_2022_2::Room::operator= (const Room &)
Copy-assignment of a Room:
Definition at line 20 of file Room.cpp.
{
        MEMBER_TRACER;
        return *this;
}
References MEMBER_TRACER.
Referenced by tracing_exam_2022_2::BathRoom::operator=(), tracing_exam_2022_2::BedRoom::operator=(), and tracing_exam_2022_2::Kitchen::operator=().
operator=() [2/2]
Room & tracing_exam_2022_2::Room::operator= (Room &&)
Move-assignment of a Room:
Definition at line 26 of file Room.cpp.
{
        MEMBER_TRACER;
        return *this;
}
References MEMBER_TRACER.
The documentation for this class was generated from the following files:
src/exams/2022_2/Room.h
src/exams/2022_2/Room.cpp