Object Tracer: Utils::FunctionTracer Class Reference
Utils::FunctionTracer Class Reference
#include <FunctionTracer.h>
Public Member Functions
FunctionTracer (const std::string &function_name)
Constructor inserts message in TrackerOutput about entering a function body.
FunctionTracer (const FunctionTracer &)=delete
No copy constructor.
FunctionTracer & operator= (const FunctionTracer &)=delete
No assignment.
~FunctionTracer ()
Destructor inserts message in TracketOutput about leaving funvtion body.
Private Attributes
std::string const m_function_name
Detailed Description
Class whose constructor/destructor pair are used to mark entering and leaving a function body block. You do this by defining an automatic variable of CodeTracker type at the beginning of the body. The constructor triggers an appropriate message.The destructor for the variable gets called when leaving the function body and triggers the appropriate message. The messages are logged through the TrackerOutput.
Definition at line 26 of file FunctionTracer.h.
Constructor & Destructor Documentation
FunctionTracer() [1/2]
FunctionTracer::FunctionTracer (const std::string & function_name) explicit
Constructor inserts message in TrackerOutput about entering a function body.
Definition at line 6 of file FunctionTracer.cpp.
                                                             : m_function_name(function_name) {
    TracerOutput::getInstance().log("---> function body: " + m_function_name);
    TracerOutput::getInstance().increase_indent();
}
References Utils::TracerOutput::getInstance(), Utils::TracerOutput::increase_indent(), Utils::TracerOutput::log(), and m_function_name.
FunctionTracer() [2/2]
Utils::FunctionTracer::FunctionTracer (const FunctionTracer &) delete
No copy constructor.
~FunctionTracer()
FunctionTracer::~FunctionTracer ()
Destructor inserts message in TracketOutput about leaving funvtion body.
Definition at line 11 of file FunctionTracer.cpp.
{
    TracerOutput::getInstance().decrease_indent();
    TracerOutput::getInstance().log("<--- function body: " + m_function_name);
}
References Utils::TracerOutput::decrease_indent(), Utils::TracerOutput::getInstance(), Utils::TracerOutput::log(), and m_function_name.
Member Function Documentation
operator=()
FunctionTracer & Utils::FunctionTracer::operator= (const FunctionTracer &) delete
No assignment.
Member Data Documentation
m_function_name
std::string const Utils::FunctionTracer::m_function_name private
Definition at line 41 of file FunctionTracer.h.
Referenced by FunctionTracer(), and ~FunctionTracer().
The documentation for this class was generated from the following files:
src/utils/FunctionTracer.h
src/utils/FunctionTracer.cpp