Object Tracer: tracing_exam_2023_1::House Class Reference
tracing_exam_2023_1::House Class Reference
#include <House.h>
Public Member Functions
House (Person &owner)
Constructor.
House (Person &&owner, unsigned int bedrooms)
Constructor.
virtual ~House ()
Destructor.
House (const House &h)
Copy Constructor.
House (House &&h)
Move Constructor.
House & operator= (const House &)
Copy-assignment of a House:
House & operator= (House &&)
Move-assignment of a House:
virtual std::string getName () const override
Returns the name of the Building.
virtual void addNeighbour (House *neighbour)
void welcome (Visitor &v) override
Accept the Visitor to this House.
Public Member Functions inherited from tracing_exam_2023_1::Building
Building (Person &owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual std::string getName () const
Returns the name of the Building.
virtual const Person & getOwner () const
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
virtual void welcome (Visitor &v)
Accept the Visitor to this Building.
Private Attributes
std::unique_ptr< Kitchen > m_kitchen = std::make_unique<Kitchen>()
BathRoom * m_bathroom
Additional Inherited Members
Protected Attributes inherited from tracing_exam_2023_1::Building
Person & m_owner
std::vector< Building * > m_neighbours
std::vector< std::unique_ptr< Room > > m_rooms
Detailed Description
Definition at line 19 of file House.h.
Constructor & Destructor Documentation
House() [1/4]
tracing_exam_2023_1::House::House (Person & owner)
Constructor.
Definition at line 18 of file House.cpp.
                          : House(std::move(owner), 2) {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
House() [2/4]
tracing_exam_2023_1::House::House (Person && owner, unsigned int bedrooms)
Constructor.
Definition at line 22 of file House.cpp.
                                                  : Building(owner), m_bathroom(new BathRoom())
{
    MEMBER_TRACER;
    for (unsigned int i = 0; i < bedrooms; i++) {
        BLOCK_TRACER("For Loop");
        BedRoom b;
        m_rooms.emplace_back(std::make_unique<BedRoom>(b));
    }
}
References BLOCK_TRACER, tracing_exam_2023_1::Building::m_rooms, and MEMBER_TRACER.
~House()
tracing_exam_2023_1::House::~House () virtual
Destructor.
Definition at line 71 of file House.cpp.
              {
    MEMBER_TRACER;
    if (m_bathroom)
        delete m_bathroom;
}
References m_bathroom, and MEMBER_TRACER.
House() [3/4]
tracing_exam_2023_1::House::House (const House & h)
Copy Constructor.
Definition at line 32 of file House.cpp.
                           : Building(h), m_kitchen(std::make_unique<Kitchen>(*h.m_kitchen)), m_bathroom(new BathRoom(*h.m_bathroom))
{
    MEMBER_TRACER;
}
References MEMBER_TRACER.
House() [4/4]
tracing_exam_2023_1::House::House (House && h)
Move Constructor.
Definition at line 37 of file House.cpp.
                      : Building(std::move(h)), m_kitchen(std::move(h.m_kitchen)), m_bathroom(h.m_bathroom)
{
    MEMBER_TRACER;
    h.m_bathroom = nullptr;
}
References MEMBER_TRACER.
Member Function Documentation
addNeighbour()
void tracing_exam_2023_1::House::addNeighbour (House * neighbour) virtual
Adds a House to the list of neighbours of the current House It does not take ownership of this neighbouring House
Definition at line 83 of file House.cpp.
{
        MEMBER_TRACER;
        if (neighbour != this) {
                m_neighbours.emplace_back(neighbour);
        }
}
References tracing_exam_2023_1::Building::m_neighbours, and MEMBER_TRACER.
getName()
std::string tracing_exam_2023_1::House::getName () const override virtual
Returns the name of the Building.
Reimplemented from tracing_exam_2023_1::Building.
Reimplemented in tracing_exam_2023_1::HolidayHome.
Definition at line 77 of file House.cpp.
{
        MEMBER_TRACER;
        return "House";
}
References MEMBER_TRACER.
operator=() [1/2]
House & tracing_exam_2023_1::House::operator= (const House & other)
Copy-assignment of a House:
Definition at line 43 of file House.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                Building::operator=(other);
                *m_bathroom = *other.m_bathroom;
                *m_kitchen = *other.m_kitchen;
        }
        return *this;
}
References m_bathroom, m_kitchen, MEMBER_TRACER, and tracing_exam_2023_1::Building::operator=().
Referenced by tracing_exam_2023_1::HolidayHome::operator=().
operator=() [2/2]
House & tracing_exam_2023_1::House::operator= (House && other)
Move-assignment of a House:
Definition at line 54 of file House.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                Building::operator=(std::move(other));
                if (m_bathroom)
                    delete m_bathroom;
                m_bathroom = other.m_bathroom;
                other.m_bathroom = nullptr;
                m_kitchen = std::move(other.m_kitchen);
        }
        return *this;
}
References m_bathroom, m_kitchen, MEMBER_TRACER, and tracing_exam_2023_1::Building::operator=().
welcome()
void tracing_exam_2023_1::House::welcome (Visitor & v) override virtual
Accept the Visitor to this House.
Reimplemented from tracing_exam_2023_1::Building.
Definition at line 91 of file House.cpp.
{
        MEMBER_TRACER;
        v.visit(this);
}
References MEMBER_TRACER, and tracing_exam_2023_1::Visitor::visit().
Member Data Documentation
m_bathroom
BathRoom* tracing_exam_2023_1::House::m_bathroom private
Definition at line 55 of file House.h.
Referenced by operator=(), and ~House().
m_kitchen
std::unique_ptr<Kitchen> tracing_exam_2023_1::House::m_kitchen = std::make_unique<Kitchen>() private
Definition at line 54 of file House.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/exams/2023_1/House.h
src/exams/2023_1/House.cpp