Object Tracer: tracing_exam_2023_1::Rentable Class Reference
tracing_exam_2023_1::Rentable Class Reference
#include <Rentable.h>
Public Member Functions
Rentable ()
Constructor.
Rentable (const Rentable &r)
Copy Constructor.
Rentable (Rentable &&r)
Move Constructor.
virtual ~Rentable ()
Destructor.
Rentable & operator= (const Rentable &)
Copy-assignment of a Rentable:
Rentable & operator= (Rentable &&)
Move-assignment of a Rentable:
void rent (const Person &renter)
Rent this Rentable.
void rent (Person &&renter)
Rent this Rentable.
Public Member Functions inherited from tracing_exam_2023_1::Subject< T >
Subject ()
virtual ~Subject ()
void attach (std::shared_ptr< Observer< T > > observer, Event e)
void notify (Event e)
Private Attributes
std::shared_ptr< Person > m_renter
Detailed Description
Definition at line 19 of file Rentable.h.
Constructor & Destructor Documentation
Rentable() [1/3]
tracing_exam_2023_1::Rentable::Rentable ()
Constructor.
Definition at line 15 of file Rentable.cpp.
: m_renter() { MEMBER_TRACER; }
References MEMBER_TRACER.
Rentable() [2/3]
tracing_exam_2023_1::Rentable::Rentable (const Rentable & r)
Copy Constructor.
Definition at line 19 of file Rentable.cpp.
: m_renter(other.m_renter) { MEMBER_TRACER; }
References MEMBER_TRACER.
Rentable() [3/3]
tracing_exam_2023_1::Rentable::Rentable (Rentable && r)
Move Constructor.
Definition at line 21 of file Rentable.cpp.
: m_renter(std::move(other.m_renter)) { MEMBER_TRACER; }
References MEMBER_TRACER.
~Rentable()
tracing_exam_2023_1::Rentable::~Rentable () virtual
Destructor.
Definition at line 17 of file Rentable.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
Rentable & tracing_exam_2023_1::Rentable::operator= (const Rentable & other)
Copy-assignment of a Rentable:
Definition at line 23 of file Rentable.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                m_renter = other.m_renter;
        }
        return *this;
}
References m_renter, and MEMBER_TRACER.
Referenced by tracing_exam_2023_1::HolidayHome::operator=().
operator=() [2/2]
Rentable & tracing_exam_2023_1::Rentable::operator= (Rentable && other)
Move-assignment of a Rentable:
Definition at line 32 of file Rentable.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                m_renter = std::move(other.m_renter);
        }
        return *this;
}
References m_renter, and MEMBER_TRACER.
rent() [1/2]
void tracing_exam_2023_1::Rentable::rent (const Person & renter)
Rent this Rentable.
Definition at line 41 of file Rentable.cpp.
{
        MEMBER_TRACER;
        if (m_renter) {
                throw std::runtime_error("This Rentable is already being rented!");
        } else {
                m_renter = std::make_shared<Person>(renter);
                notify(Event::BuildingRented);
        }
}
References tracing_exam_2023_1::BuildingRented, m_renter, MEMBER_TRACER, and tracing_exam_2023_1::Subject< T >::notify().
Referenced by app_exam_2023_1(), and rent().
rent() [2/2]
void tracing_exam_2023_1::Rentable::rent (Person && renter)
Rent this Rentable.
Definition at line 52 of file Rentable.cpp.
{
        MEMBER_TRACER;
        rent(renter);
}
References MEMBER_TRACER, and rent().
Member Data Documentation
m_renter
std::shared_ptr<Person> tracing_exam_2023_1::Rentable::m_renter private
Definition at line 47 of file Rentable.h.
Referenced by operator=(), and rent().
The documentation for this class was generated from the following files:
src/exams/2023_1/Rentable.h
src/exams/2023_1/Rentable.cpp