Object Tracer: tracing_exam_2023_1::HolidayHome Class Reference
tracing_exam_2023_1::HolidayHome Class Reference
#include <HolidayHome.h>
Public Member Functions
HolidayHome (Person &owner, unsigned int bedrooms)
Constructor.
HolidayHome (Person &owner)
Constructor.
HolidayHome (const HolidayHome &h)
Copy Constructor.
HolidayHome (HolidayHome &&h)
Move Constructor.
virtual ~HolidayHome ()
Destructor.
HolidayHome & operator= (const HolidayHome &)
Copy-assignment of a HolidayHome:
HolidayHome & operator= (HolidayHome &&)
Move-assignment of a HolidayHome:
virtual std::string getName () const override
Returns the name of the Building.
virtual void addNeighbour (HolidayHome *neighbour)
void welcome (Visitor &v) override
Accept the Visitor to this HolidayHome.
Public Member Functions inherited from tracing_exam_2023_1::Rentable
Rentable ()
Constructor.
Rentable (const Rentable &r)
Copy Constructor.
Rentable (Rentable &&r)
Move Constructor.
virtual ~Rentable ()
Destructor.
Rentable & operator= (const Rentable &)
Copy-assignment of a Rentable:
Rentable & operator= (Rentable &&)
Move-assignment of a Rentable:
void rent (const Person &renter)
Rent this Rentable.
void rent (Person &&renter)
Rent this Rentable.
Public Member Functions inherited from tracing_exam_2023_1::Subject< T >
Subject ()
virtual ~Subject ()
void attach (std::shared_ptr< Observer< T > > observer, Event e)
void notify (Event e)
Public Member Functions inherited from tracing_exam_2023_1::House
House (Person &owner)
Constructor.
House (Person &&owner, unsigned int bedrooms)
Constructor.
virtual ~House ()
Destructor.
House (const House &h)
Copy Constructor.
House (House &&h)
Move Constructor.
House & operator= (const House &)
Copy-assignment of a House:
House & operator= (House &&)
Move-assignment of a House:
virtual std::string getName () const override
Returns the name of the Building.
virtual void addNeighbour (House *neighbour)
void welcome (Visitor &v) override
Accept the Visitor to this House.
Public Member Functions inherited from tracing_exam_2023_1::Building
Building (Person &owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual std::string getName () const
Returns the name of the Building.
virtual const Person & getOwner () const
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
virtual void welcome (Visitor &v)
Accept the Visitor to this Building.
Additional Inherited Members
Protected Attributes inherited from tracing_exam_2023_1::Building
Person & m_owner
std::vector< Building * > m_neighbours
std::vector< std::unique_ptr< Room > > m_rooms
Detailed Description
Definition at line 16 of file HolidayHome.h.
Constructor & Destructor Documentation
HolidayHome() [1/4]
tracing_exam_2023_1::HolidayHome::HolidayHome (Person & owner, unsigned int bedrooms)
Constructor.
Definition at line 13 of file HolidayHome.cpp.
: House(std::move(owner), bedrooms) { MEMBER_TRACER; }
References MEMBER_TRACER.
HolidayHome() [2/4]
tracing_exam_2023_1::HolidayHome::HolidayHome (Person & owner)
Constructor.
Definition at line 15 of file HolidayHome.cpp.
: House(owner) { MEMBER_TRACER; }
References MEMBER_TRACER.
HolidayHome() [3/4]
tracing_exam_2023_1::HolidayHome::HolidayHome (const HolidayHome & h)
Copy Constructor.
Definition at line 19 of file HolidayHome.cpp.
: Rentable(h), House(h) { MEMBER_TRACER; }
References MEMBER_TRACER.
HolidayHome() [4/4]
tracing_exam_2023_1::HolidayHome::HolidayHome (HolidayHome && h)
Move Constructor.
Definition at line 21 of file HolidayHome.cpp.
: Rentable(std::move(h)), House(std::move(h)) { MEMBER_TRACER; }
References MEMBER_TRACER.
~HolidayHome()
tracing_exam_2023_1::HolidayHome::~HolidayHome () virtual
Destructor.
Definition at line 17 of file HolidayHome.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
addNeighbour()
void tracing_exam_2023_1::HolidayHome::addNeighbour (HolidayHome * neighbour) virtual
Adds a HolidayHome to the list of neighbours of the current House It does not take ownership of this neighbouring HolidayHome
Definition at line 49 of file HolidayHome.cpp.
{
        MEMBER_TRACER;
        if (neighbour != this) {
                m_neighbours.emplace_back(neighbour);
        }
}
References tracing_exam_2023_1::Building::m_neighbours, and MEMBER_TRACER.
getName()
std::string tracing_exam_2023_1::HolidayHome::getName () const override virtual
Returns the name of the Building.
Reimplemented from tracing_exam_2023_1::House.
Definition at line 43 of file HolidayHome.cpp.
{
        MEMBER_TRACER;
        return "HolidayHome";
}
References MEMBER_TRACER.
operator=() [1/2]
HolidayHome & tracing_exam_2023_1::HolidayHome::operator= (const HolidayHome & other)
Copy-assignment of a HolidayHome:
Definition at line 23 of file HolidayHome.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                House::operator=(other);
                Rentable::operator=(other);
        }
        return *this;
}
References MEMBER_TRACER, tracing_exam_2023_1::House::operator=(), and tracing_exam_2023_1::Rentable::operator=().
operator=() [2/2]
HolidayHome & tracing_exam_2023_1::HolidayHome::operator= (HolidayHome && other)
Move-assignment of a HolidayHome:
Definition at line 33 of file HolidayHome.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                House::operator=(std::move(other));
                Rentable::operator=(std::move(other));
        }
        return *this;
}
References MEMBER_TRACER, tracing_exam_2023_1::House::operator=(), and tracing_exam_2023_1::Rentable::operator=().
welcome()
void tracing_exam_2023_1::HolidayHome::welcome (Visitor & v) override virtual
Accept the Visitor to this HolidayHome.
Reimplemented from tracing_exam_2023_1::Building.
Definition at line 57 of file HolidayHome.cpp.
{
        MEMBER_TRACER;
        v.visit(this);
}
References MEMBER_TRACER, and tracing_exam_2023_1::Visitor::visit().
The documentation for this class was generated from the following files:
src/exams/2023_1/HolidayHome.h
src/exams/2023_1/HolidayHome.cpp