Object Tracer: Vehicles::RoadVehicle Class Reference
Vehicles::RoadVehicle Class Reference
#include <RoadVehicle.h>
Public Member Functions
RoadVehicle ()
Default constructor.
RoadVehicle (const RoadVehicle &ori)
Copy constructor.
RoadVehicle (RoadVehicle &&ori) noexcept
Move constructor.
RoadVehicle & operator= (const RoadVehicle &rhs)
Copy assignment operator.
RoadVehicle & operator= (RoadVehicle &&rhs) noexcept
Move assignment operator.
~RoadVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Motion of the vehicle.
Public Member Functions inherited from Vehicles::LandVehicle
LandVehicle ()
default constructor.
LandVehicle (const LandVehicle &ori)
Copy constructor.
LandVehicle (LandVehicle &&ori) noexcept
Move constructor.
LandVehicle & operator= (const LandVehicle &rhs)
Copy assignment.
LandVehicle & operator= (LandVehicle &&rhs) noexcept
Move assignment.
~LandVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override=0
Pure virtual function: motion for the LandVehicle.
Public Member Functions inherited from Vehicles::Vehicle
virtual ~Vehicle ()=default
Destructor.
virtual void info () const =0
Return vehicle information.
virtual void move (double speed, std::vector< double > direction)=0
Motion of vehicle.
Detailed Description
A RoadVehicle is any kind of vehicle that moves on the road.
Definition at line 11 of file RoadVehicle.h.
Constructor & Destructor Documentation
RoadVehicle() [1/3]
Vehicles::RoadVehicle::RoadVehicle ()
Default constructor.
Definition at line 8 of file RoadVehicle.cpp.
: LandVehicle() { MEMBER_TRACER; }
References MEMBER_TRACER.
RoadVehicle() [2/3]
Vehicles::RoadVehicle::RoadVehicle (const RoadVehicle & ori)
Copy constructor.
Definition at line 10 of file RoadVehicle.cpp.
: LandVehicle(ori) { MEMBER_TRACER; }
References MEMBER_TRACER.
RoadVehicle() [3/3]
Vehicles::RoadVehicle::RoadVehicle (RoadVehicle && ori) noexcept
Move constructor.
Definition at line 12 of file RoadVehicle.cpp.
: LandVehicle(std::move(ori)) { MEMBER_TRACER; }
References MEMBER_TRACER.
~RoadVehicle()
Vehicles::RoadVehicle::~RoadVehicle () override
Destructor.
Definition at line 30 of file RoadVehicle.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
info()
void Vehicles::RoadVehicle::info () const override virtual
Return identification info.
Reimplemented from Vehicles::LandVehicle.
Definition at line 32 of file RoadVehicle.cpp.
{
    MEMBER_TRACER;
    const string s{"I'm a generic Road vehicle"};
    LOG_TRACER(s);
}
References LOG_TRACER, and MEMBER_TRACER.
move()
void Vehicles::RoadVehicle::move (double speed, std::vector< double > direction) override virtual
Motion of the vehicle.
Implements Vehicles::LandVehicle.
Definition at line 38 of file RoadVehicle.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
operator=() [1/2]
RoadVehicle & Vehicles::RoadVehicle::operator= (const RoadVehicle & rhs)
Copy assignment operator.
Definition at line 14 of file RoadVehicle.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        LandVehicle::operator=(rhs);
    }
    return *this;
}
References MEMBER_TRACER, and Vehicles::LandVehicle::operator=().
Referenced by Vehicles::PassengerRoadVehicle::operator=().
operator=() [2/2]
RoadVehicle & Vehicles::RoadVehicle::operator= (RoadVehicle && rhs) noexcept
Move assignment operator.
Definition at line 22 of file RoadVehicle.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        LandVehicle::operator=(rhs);
    }
    return *this;
}
References MEMBER_TRACER, and Vehicles::LandVehicle::operator=().
The documentation for this class was generated from the following files:
src/vehicles/RoadVehicle.h
src/vehicles/RoadVehicle.cpp