Object Tracer: tracing_exam_2023_1::Visitor Class Reference
tracing_exam_2023_1::Visitor Class Reference
#include <Visitor.h>
Public Member Functions
Visitor ()
Constructor.
~Visitor ()
Destructor.
template<typename T >
void visit (T *t)
Detailed Description
Definition at line 21 of file Visitor.h.
Constructor & Destructor Documentation
Visitor()
tracing_exam_2023_1::Visitor::Visitor ()
Constructor.
Definition at line 13 of file Visitor.cpp.
                 {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
~Visitor()
tracing_exam_2023_1::Visitor::~Visitor ()
Destructor.
Definition at line 17 of file Visitor.cpp.
                  {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
Member Function Documentation
visit()
template<typename T > void tracing_exam_2023_1::Visitor::visit (T * t) inline
Visit the provided object Make sure you provide the actual type T for each template instantiation For example: —> function body: void tracing_exam_2023_1::Visitor::visit(T*) [with T = tracing_exam_2023_1::Building]
Definition at line 34 of file Visitor.h.
{
            MEMBER_TRACER;
            LOG_TRACER("Visiting a " + t->getName());
        }
References LOG_TRACER, and MEMBER_TRACER.
Referenced by tracing_exam_2023_1::Building::welcome(), tracing_exam_2023_1::HolidayHome::welcome(), and tracing_exam_2023_1::House::welcome().
The documentation for this class was generated from the following files:
src/exams/2023_1/Visitor.h
src/exams/2023_1/Visitor.cpp