Object Tracer: tracing_exam_2022_2::House Class Reference
tracing_exam_2022_2::House Class Reference
#include <House.h>
Public Member Functions
House (Person owner, unsigned int bedrooms)
Constructor.
virtual ~House ()
Destructor.
House (const House &h)
Copy Constructor.
House (House &&h)
Move Constructor.
House & operator= (const House &)
Copy-assignment of a House:
House & operator= (House &&)
Move-assignment of a House:
virtual std::string getName () const override
Returns the name of the Building.
virtual void addNeighbour (House *neighbour)
void welcome (Visitor &v) override
Accept the Visitor to this House.
Public Member Functions inherited from tracing_exam_2022_2::Building
Building (Person &owner)
Constructor.
Building (const Person &owner)
Constructor.
Building (Person &&owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual std::string getName () const
Returns the name of the Building.
virtual Person & getOwner ()
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
virtual void welcome (Visitor &v)
Accept the Visitor to this Building.
Private Attributes
std::shared_ptr< const BathRoom > m_bathroom = std::make_shared<const BathRoom>()
Kitchen m_kitchen
Additional Inherited Members
Protected Attributes inherited from tracing_exam_2022_2::Building
std::vector< std::shared_ptr< const Room > > m_rooms
std::vector< Building * > m_neighbours
Person m_owner
Detailed Description
Definition at line 19 of file House.h.
Constructor & Destructor Documentation
House() [1/3]
tracing_exam_2022_2::House::House (Person owner, unsigned int bedrooms)
Constructor.
Definition at line 18 of file House.cpp.
                                                : Building(std::move(owner)), m_kitchen()
{
        MEMBER_TRACER;
        for (unsigned int i = 0; i < bedrooms; i++) {
                m_rooms.emplace_back(std::make_shared<const BedRoom>());
        }
        m_rooms.emplace_back(m_bathroom);
}
References m_bathroom, tracing_exam_2022_2::Building::m_rooms, and MEMBER_TRACER.
~House()
tracing_exam_2022_2::House::~House () virtual
Destructor.
Definition at line 60 of file House.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
House() [2/3]
tracing_exam_2022_2::House::House (const House & h)
Copy Constructor.
Definition at line 28 of file House.cpp.
                           : Building(h), m_bathroom(h.m_bathroom), m_kitchen(h.m_kitchen)
{
        MEMBER_TRACER;
}
References MEMBER_TRACER.
House() [3/3]
tracing_exam_2022_2::House::House (House && h)
Move Constructor.
Definition at line 33 of file House.cpp.
                      : Building(std::move(h)), m_bathroom(std::move(h.m_bathroom)), m_kitchen(std::move(h.m_kitchen))
{
        MEMBER_TRACER;
}
References MEMBER_TRACER.
Member Function Documentation
addNeighbour()
void tracing_exam_2022_2::House::addNeighbour (House * neighbour) virtual
Adds a House to the list of neighbours of the current House It does not take ownership of this neighbouring House
Definition at line 68 of file House.cpp.
{
        MEMBER_TRACER;
        if (neighbour != this) {
                m_neighbours.emplace_back(neighbour);
        }
}
References tracing_exam_2022_2::Building::m_neighbours, and MEMBER_TRACER.
getName()
std::string tracing_exam_2022_2::House::getName () const override virtual
Returns the name of the Building.
Reimplemented from tracing_exam_2022_2::Building.
Reimplemented in tracing_exam_2022_2::HolidayHome.
Definition at line 62 of file House.cpp.
{
        MEMBER_TRACER;
        return "House";
}
References MEMBER_TRACER.
operator=() [1/2]
House & tracing_exam_2022_2::House::operator= (const House & other)
Copy-assignment of a House:
Definition at line 38 of file House.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                Building::operator=(other);
                m_bathroom = other.m_bathroom;
                m_kitchen = other.m_kitchen;
        }
        return *this;
}
References m_bathroom, m_kitchen, MEMBER_TRACER, and tracing_exam_2022_2::Building::operator=().
Referenced by tracing_exam_2022_2::HolidayHome::operator=().
operator=() [2/2]
House & tracing_exam_2022_2::House::operator= (House && other)
Move-assignment of a House:
Definition at line 49 of file House.cpp.
{
        MEMBER_TRACER;
        if (this != &other) {
                Building::operator=(std::move(other));
                m_bathroom = std::move(other.m_bathroom);
                m_kitchen = std::move(other.m_kitchen);
        }
        return *this;
}
References m_bathroom, m_kitchen, MEMBER_TRACER, and tracing_exam_2022_2::Building::operator=().
welcome()
void tracing_exam_2022_2::House::welcome (Visitor & v) override virtual
Accept the Visitor to this House.
Reimplemented from tracing_exam_2022_2::Building.
Definition at line 76 of file House.cpp.
{
        MEMBER_TRACER;
        v.visit(this);
}
References MEMBER_TRACER, and tracing_exam_2022_2::Visitor::visit().
Member Data Documentation
m_bathroom
std::shared_ptr<const BathRoom> tracing_exam_2022_2::House::m_bathroom = std::make_shared<const BathRoom>() private
Definition at line 51 of file House.h.
Referenced by House(), and operator=().
m_kitchen
Kitchen tracing_exam_2022_2::House::m_kitchen private
Definition at line 52 of file House.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/exams/2022_2/House.h
src/exams/2022_2/House.cpp