Object Tracer: Vehicles::Bicycle Class Reference
Vehicles::Bicycle Class Reference
#include <Bicycle.h>
Public Member Functions
Bicycle ()
Default constructor.
Bicycle (std::string model, std::string color)
Parametrized contructor, initialize model and color.
Bicycle (const Bicycle &ori)
Copy constructor.
Bicycle (Bicycle &&ori) noexcept
Move constructor.
Bicycle & operator= (const Bicycle &rhs)
Copy assignment.
Bicycle & operator= (Bicycle &&rhs) noexcept
Move assignment.
~Bicycle () override
Destructor.
std::string getModel () const
Return the model of the bike.
std::string getColor () const
Return the color of the bike.
void setModel (std::string model)
Set the model of the bike.
void setColor (std::string color)
Set the color of the bike.
void info () const override
Display info on model and color of the bike.
Public Member Functions inherited from Vehicles::PassengerRoadVehicle
PassengerRoadVehicle (int numSeats)
Parametrized constructor, initializes number of seats.
PassengerRoadVehicle (PassengerRoadVehicle const &ori)
Copy constructor.
PassengerRoadVehicle (PassengerRoadVehicle &&ori) noexcept
Move constructor.
PassengerRoadVehicle & operator= (PassengerRoadVehicle const &rhs)
Copy assignment.
PassengerRoadVehicle & operator= (PassengerRoadVehicle &&rhs) noexcept
Move assignment.
~PassengerRoadVehicle () override
Destructor.
bool add_passenger ()
Take an additional passenger on board, if possible.
bool remove_passenger ()
Remove a passenger, if possible.
int get_capacity () const
Return the number of seats on the vehicle.
int get_free () const
Return the number of seats still free.
void info () const override
Return identification info.
Public Member Functions inherited from Vehicles::RoadVehicle
RoadVehicle ()
Default constructor.
RoadVehicle (const RoadVehicle &ori)
Copy constructor.
RoadVehicle (RoadVehicle &&ori) noexcept
Move constructor.
RoadVehicle & operator= (const RoadVehicle &rhs)
Copy assignment operator.
RoadVehicle & operator= (RoadVehicle &&rhs) noexcept
Move assignment operator.
~RoadVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Motion of the vehicle.
Public Member Functions inherited from Vehicles::LandVehicle
LandVehicle ()
default constructor.
LandVehicle (const LandVehicle &ori)
Copy constructor.
LandVehicle (LandVehicle &&ori) noexcept
Move constructor.
LandVehicle & operator= (const LandVehicle &rhs)
Copy assignment.
LandVehicle & operator= (LandVehicle &&rhs) noexcept
Move assignment.
~LandVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override=0
Pure virtual function: motion for the LandVehicle.
Public Member Functions inherited from Vehicles::Vehicle
virtual ~Vehicle ()=default
Destructor.
virtual void info () const =0
Return vehicle information.
virtual void move (double speed, std::vector< double > direction)=0
Motion of vehicle.
Private Attributes
std::string m_model
std::string m_color
Detailed Description
Represents a simple Bicycle.
Definition at line 11 of file Bicycle.h.
Constructor & Destructor Documentation
Bicycle() [1/4]
Vehicles::Bicycle::Bicycle ()
Default constructor.
Definition at line 8 of file Bicycle.cpp.
: PassengerRoadVehicle(2), m_model("Unknown model"), m_color("Unknown color") { MEMBER_TRACER; }
References MEMBER_TRACER.
Bicycle() [2/4]
Vehicles::Bicycle::Bicycle (std::string model, std::string color)
Parametrized contructor, initialize model and color.
Definition at line 10 of file Bicycle.cpp.
    : PassengerRoadVehicle(2), m_model(std::move(model)), m_color(std::move(color)) {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
Bicycle() [3/4]
Vehicles::Bicycle::Bicycle (const Bicycle & ori)
Copy constructor.
Definition at line 15 of file Bicycle.cpp.
                                   : PassengerRoadVehicle(ori), m_model(ori.m_model), m_color(ori.m_color) {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
Bicycle() [4/4]
Vehicles::Bicycle::Bicycle (Bicycle && ori) noexcept
Move constructor.
Definition at line 19 of file Bicycle.cpp.
    : PassengerRoadVehicle(std::move(ori)), m_model(std::move(ori.m_model)), m_color(std::move(ori.m_color)) {
    MEMBER_TRACER;
}
References MEMBER_TRACER.
~Bicycle()
Vehicles::Bicycle::~Bicycle () override
Destructor.
Definition at line 48 of file Bicycle.cpp.
{ MEMBER_TRACER; }
References MEMBER_TRACER.
Member Function Documentation
getColor()
string Vehicles::Bicycle::getColor () const
Return the color of the bike.
Definition at line 55 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    return m_color;
}
References m_color, and MEMBER_TRACER.
getModel()
string Vehicles::Bicycle::getModel () const
Return the model of the bike.
Definition at line 50 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    return m_model;
}
References m_model, and MEMBER_TRACER.
info()
void Vehicles::Bicycle::info () const override virtual
Display info on model and color of the bike.
Implements Vehicles::Vehicle.
Definition at line 70 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    const string s = {"I'm a bicycle: model = " + m_model + ", color = " + m_color};
    LOG_TRACER(s);
}
References LOG_TRACER, m_color, m_model, and MEMBER_TRACER.
Referenced by app_exception(), and app_hierarchies().
operator=() [1/2]
Bicycle & Vehicles::Bicycle::operator= (Bicycle && rhs) noexcept
Move assignment.
Definition at line 34 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        PassengerRoadVehicle::operator=(std::move(rhs));
        m_model = std::move(rhs.m_model);
        m_color = std::move(rhs.m_color);
        // Leave the argument in an indeterminate state.
        rhs.m_model = "";
        rhs.m_color = "";
    }
    return *this;
}
References MEMBER_TRACER, and Vehicles::PassengerRoadVehicle::operator=().
operator=() [2/2]
Bicycle & Vehicles::Bicycle::operator= (const Bicycle & rhs)
Copy assignment.
Definition at line 24 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    if (this != &rhs) {
        PassengerRoadVehicle::operator=(rhs);
        this->m_model = rhs.m_model;
        this->m_color = rhs.m_color;
    }
    return *this;
}
References m_color, m_model, MEMBER_TRACER, and Vehicles::PassengerRoadVehicle::operator=().
setColor()
void Vehicles::Bicycle::setColor (std::string color)
Set the color of the bike.
Definition at line 65 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    m_color = std::move(color);
}
References m_color, and MEMBER_TRACER.
setModel()
void Vehicles::Bicycle::setModel (std::string model)
Set the model of the bike.
Definition at line 60 of file Bicycle.cpp.
{
    MEMBER_TRACER;
    m_model = std::move(model);
}
References m_model, and MEMBER_TRACER.
Member Data Documentation
m_color
std::string Vehicles::Bicycle::m_color private
Definition at line 51 of file Bicycle.h.
Referenced by getColor(), info(), operator=(), and setColor().
m_model
std::string Vehicles::Bicycle::m_model private
Definition at line 50 of file Bicycle.h.
Referenced by getModel(), info(), operator=(), and setModel().
The documentation for this class was generated from the following files:
src/vehicles/Bicycle.h
src/vehicles/Bicycle.cpp