Object Tracer: Utils::TracerOutput Class Reference
Utils::TracerOutput Class Reference
#include <TracerOutput.h>
Public Member Functions
bool is_output_on ()
Indicate whether current making output.
void set_output_on ()
Start making output (ok even output already started).
void set_output_off ()
Stop making output (ok even if output already stopped).
void increase_indent ()
Increase the indentation level.
void decrease_indent ()
Decrease the indentation level.
void log (const std::string &msg)
Insert the message in the google log at given severity level.
TracerOutput (TracerOutput const &)=delete
void operator= (TracerOutput const &)=delete
Static Public Member Functions
static TracerOutput & getInstance ()
Get the TracerOutput instance.
Private Member Functions
TracerOutput ()=default
Private Attributes
bool m_make_output {true}
unsigned int m_indent {0}
std::ostringstream m_output
Friends
std::ostream & operator<< (std::ostream &, const TracerOutput &)
Get the output of this TracerOutput instance.
Detailed Description
Definition at line 12 of file TracerOutput.h.
Constructor & Destructor Documentation
TracerOutput() [1/2]
Utils::TracerOutput::TracerOutput (TracerOutput const &) delete
TracerOutput() [2/2]
Utils::TracerOutput::TracerOutput () private default
Member Function Documentation
decrease_indent()
void Utils::TracerOutput::decrease_indent ()
Decrease the indentation level.
Definition at line 16 of file TracerOutput.cpp.
{ m_indent--; }
References m_indent.
Referenced by Utils::BlockTracer::~BlockTracer(), Utils::FunctionTracer::~FunctionTracer(), and Utils::MemberTracer::~MemberTracer().
getInstance()
TracerOutput & Utils::TracerOutput::getInstance () static
Get the TracerOutput instance.
Definition at line 27 of file TracerOutput.cpp.
{
    static TracerOutput instance;
    return instance;
}
Referenced by Utils::BlockTracer::BlockTracer(), Utils::FunctionTracer::FunctionTracer(), main(), Utils::MemberTracer::MemberTracer(), Utils::BlockTracer::~BlockTracer(), Utils::FunctionTracer::~FunctionTracer(), and Utils::MemberTracer::~MemberTracer().
increase_indent()
void Utils::TracerOutput::increase_indent ()
Increase the indentation level.
Definition at line 14 of file TracerOutput.cpp.
{ m_indent++; }
References m_indent.
Referenced by Utils::BlockTracer::BlockTracer(), Utils::FunctionTracer::FunctionTracer(), and Utils::MemberTracer::MemberTracer().
is_output_on()
bool Utils::TracerOutput::is_output_on ()
Indicate whether current making output.
Definition at line 8 of file TracerOutput.cpp.
{ return m_make_output; }
References m_make_output.
Referenced by log().
log()
void Utils::TracerOutput::log (const std::string & msg)
Insert the message in the google log at given severity level.
Definition at line 18 of file TracerOutput.cpp.
{
    if (is_output_on()) {
        for (unsigned int i = 0; i < m_indent; ++i) {
            m_output << "     ";
        }
        m_output << msg << std::endl;
    }
}
References is_output_on(), m_indent, and m_output.
Referenced by Utils::BlockTracer::BlockTracer(), Utils::FunctionTracer::FunctionTracer(), Utils::MemberTracer::MemberTracer(), Utils::BlockTracer::~BlockTracer(), Utils::FunctionTracer::~FunctionTracer(), and Utils::MemberTracer::~MemberTracer().
operator=()
void Utils::TracerOutput::operator= (TracerOutput const &) delete
set_output_off()
void Utils::TracerOutput::set_output_off ()
Stop making output (ok even if output already stopped).
Definition at line 12 of file TracerOutput.cpp.
{ m_make_output = false; }
References m_make_output.
set_output_on()
void Utils::TracerOutput::set_output_on ()
Start making output (ok even output already started).
Definition at line 10 of file TracerOutput.cpp.
{ m_make_output = true; }
References m_make_output.
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & , const TracerOutput &) friend
Get the output of this TracerOutput instance.
Member Data Documentation
m_indent
unsigned int Utils::TracerOutput::m_indent {0} private
Definition at line 45 of file TracerOutput.h.
Referenced by decrease_indent(), increase_indent(), and log().
m_make_output
bool Utils::TracerOutput::m_make_output {true} private
Definition at line 44 of file TracerOutput.h.
Referenced by is_output_on(), set_output_off(), and set_output_on().
m_output
std::ostringstream Utils::TracerOutput::m_output private
Definition at line 46 of file TracerOutput.h.
Referenced by log(), and Utils::operator<<().
The documentation for this class was generated from the following files:
src/utils/TracerOutput.h
src/utils/TracerOutput.cpp