Object Tracer: Utils::BlockTracer Class Reference
Utils::BlockTracer Class Reference
#include <BlockTracer.h>
Public Member Functions
BlockTracer (const std::string &msg)
Constructor insert message in TrackerOutput about entering a block.
BlockTracer (const BlockTracer &)=delete
No copy constructor.
BlockTracer & operator= (const BlockTracer &)=delete
No assignment.
~BlockTracer ()
Destructor inserts message in TracerOutput about leaving a block.
Private Attributes
const std::string m_msg
Detailed Description
Class whose constructor/destructor pair are used to mark entering and leaving a code block. You do this by defining an automatic variable of BlockTracer type at the beginning of the block. The constructor triggers an appropriate message.The destructor for the variable gets called when leaving the block and triggers the appropriate message. The messages are logged through the tarcer log.
Definition at line 20 of file BlockTracer.h.
Constructor & Destructor Documentation
BlockTracer() [1/2]
BlockTracer::BlockTracer (const std::string & msg) explicit
Constructor insert message in TrackerOutput about entering a block.
Definition at line 5 of file BlockTracer.cpp.
                                             : m_msg(msg) {
    TracerOutput::getInstance().log("---> code block: " + m_msg);
    TracerOutput::getInstance().increase_indent();
}
References Utils::TracerOutput::getInstance(), Utils::TracerOutput::increase_indent(), Utils::TracerOutput::log(), and m_msg.
BlockTracer() [2/2]
Utils::BlockTracer::BlockTracer (const BlockTracer &) delete
No copy constructor.
~BlockTracer()
BlockTracer::~BlockTracer ()
Destructor inserts message in TracerOutput about leaving a block.
Definition at line 10 of file BlockTracer.cpp.
{
    TracerOutput::getInstance().decrease_indent();
    TracerOutput::getInstance().log("<---  code block: " + m_msg);
}
References Utils::TracerOutput::decrease_indent(), Utils::TracerOutput::getInstance(), Utils::TracerOutput::log(), and m_msg.
Member Function Documentation
operator=()
BlockTracer & Utils::BlockTracer::operator= (const BlockTracer &) delete
No assignment.
Member Data Documentation
m_msg
const std::string Utils::BlockTracer::m_msg private
Definition at line 35 of file BlockTracer.h.
Referenced by BlockTracer(), and ~BlockTracer().
The documentation for this class was generated from the following files:
src/utils/BlockTracer.h
src/utils/BlockTracer.cpp