Object Tracer: src/exercises/demos.h File Reference
demos.h File Reference
Functions
int app_copy ()
int app_essentialops ()
int app_exception ()
int app_fcalls ()
int app_hierarchies ()
int app_poly1 ()
int app_poly2 ()
int app_exam_2021_1 ()
int app_exam_2021_2 ()
int app_exam_2022_1 ()
int app_exam_2022_2 ()
Function Documentation
app_copy()
int app_copy ()
Demo prog to demonstrate deep & shallow copy operations.
Returns
status
Exceptions
None.
Definition at line 16 of file app_copy.cpp.
               {
    FUNCTION_TRACER;
    LOG_TRACER(" statement: shared_ptr<Engine> e1Ptr(new Engine(100));");
    shared_ptr<Engine> e1Ptr(new Engine(100));
    LOG_TRACER(" statement: Person* p1Ptr = new Person(\"Owner 1\");");
    auto p1Ptr = new Person("Owner 1");
    LOG_TRACER(" statement: Motorcycle* m1Ptr = new Motorcycle(e1Ptr, p1Ptr);");
    auto m1Ptr = new Motorcycle(e1Ptr, p1Ptr);
    LOG_TRACER(" statement: m1Ptr->startEngine();");
    m1Ptr->startEngine();
    LOG_TRACER(" statement: Motorcycle* m2Ptr = new Motorcycle(*m1Ptr);");
    auto m2Ptr = new Motorcycle(*m1Ptr);
    LOG_TRACER(" statement: Motorcycle m3(shared_ptr<Engine>(new Engine(77)));");
    Motorcycle m3(make_shared<Engine>(77));
    LOG_TRACER(" statement: m3 = *m2Ptr;");
    m3 = *m2Ptr;
    LOG_TRACER(" statement: m3.stopEngine();");
    m3.stopEngine();
    LOG_TRACER(" statement: delete p1Ptr;");
    delete p1Ptr;
    LOG_TRACER(" statement: delete m1Ptr;");
    delete m1Ptr;
    LOG_TRACER(" statement: delete m2Ptr;");
    delete m2Ptr;
    LOG_TRACER(" statement: return 0;");
    return 0;
}
References FUNCTION_TRACER, LOG_TRACER, and Vehicles::Motorcycle::stopEngine().
Referenced by main().
app_essentialops()
int app_essentialops ()
Demo prog for features of ctor/dtor.
Returns
status
Exceptions
None.
Definition at line 16 of file app_essentialops.cpp.
                       {
    FUNCTION_TRACER;
    {
        BLOCK_TRACER("First block");
        LOG_TRACER(" statement: shared_ptr<Engine> e1(new Engine(50));");
        shared_ptr<Engine> e1(new Engine(50));
        LOG_TRACER(" statement: Unicycle u1();");
        Unicycle u1;
        LOG_TRACER(" statement: Motorcycle m1(&e1);");
        Motorcycle m1(e1);
    }
    {
        BLOCK_TRACER("Second block");
        LOG_TRACER(" statement: Motorcycle m1;");
        Motorcycle m1;
        LOG_TRACER(" statement: m.accelerate(1.0);");
        m1.accelerate(1.0);
        LOG_TRACER(" statement: Motorcycle m2(m1);");
        Motorcycle m2(m1);
        LOG_TRACER(" statement: Motorcycle m3(std::move(m1));");
        Motorcycle m3(std::move(m1));
        LOG_TRACER(" statement: m3 = std::move(m2);");
        m3 = std::move(m2);
    }
    {
        BLOCK_TRACER("Block for free store ctor/dtor");
        LOG_TRACER(" statement: shared_ptr<Engine> ep1(new Engine(80));");
        shared_ptr<Engine> ep1(new Engine(80));
        LOG_TRACER(" statement: auto mp1 = new Motorcycle(ep1);");
        auto mp1 = new Motorcycle(ep1);
        LOG_TRACER(" statement: delete mp1;");
        delete mp1;
    }
    LOG_TRACER(" statement: return 0;");
    return 0;
}
References Vehicles::Motorcycle::accelerate(), BLOCK_TRACER, FUNCTION_TRACER, and LOG_TRACER.
Referenced by main().
app_exam_2021_1()
int app_exam_2021_1 ()
Definition at line 17 of file app_exam_2021_1.cpp.
                      {
    FUNCTION_TRACER;
    {
        BLOCK_TRACER("First block");
        LOG_TRACER("statement: Person p1(\"Steve\");");
        Person p1("Steve"); // Note that this is tracing_example_exam::Person, not Vehicle::Person!
        LOG_TRACER("statement: Person p2(\"Peter\");");
        Person p2("Peter");
        LOG_TRACER("statement: HolidayHome h1(p1, 1);");
        HolidayHome h1(p1, 1);
        LOG_TRACER("statement: HolidayHome* h2 = new HolidayHome(p2, 2)");
        HolidayHome* h2 = new HolidayHome(p2, 2);
        LOG_TRACER("statement: h1 = *h2;");
        h1 = *h2;
        LOG_TRACER("statement: Building* h3 = &h1;");
        Building* h3 = &h1;
        LOG_TRACER("statement: h3 = h2;");
        h3 = h2;
        LOG_TRACER("statement: h3->addNeighbour(&h1);");
        h3->addNeighbour(&h1);
        LOG_TRACER("statement: h1.addNeighbour(h2);");
        h1.addNeighbour(h2);
        LOG_TRACER("statement: h1.info();");
        h1.info();
        LOG_TRACER("statement: h1 = std::move(*h2);");
        h1 = std::move(*h2);
        LOG_TRACER("statement: delete h2;");
        delete h2;
        LOG_TRACER("End of the first block");
    }
    {
        BLOCK_TRACER("Second block");
        try {
            BLOCK_TRACER("Try block");
            TRACER_OUTPUT_OFF;    // Temporarily setting  the  log  output OFF
            Person p1("Steve");   // Should not produce any logs
            Person p2("Peter");   // Should not produce any logs
            Person p3("Harry");   // Should not produce any logs
            HolidayHome h(p1, 1); // Should not produce any logs
            TRACER_OUTPUT_ON;     // Setting  the  log  output back ON,
                                  // including for objects created when it was OFF
            LOG_TRACER("statement: h.rent(p2);");
            h.rent(p2);
            LOG_TRACER("statement: h.rent(p3);");
            h.rent(p3);
            LOG_TRACER("statement: h.info();");
            h.info();
        } catch (std::runtime_error& e) {
            LOG_TRACER(e.what());
        }
        LOG_TRACER("End of the second block");
    }
    LOG_TRACER("statement: return 0;");
    return 0;
}
References tracing_exam_2021::Building::addNeighbour(), tracing_exam_2021::HolidayHome::addNeighbour(), BLOCK_TRACER, FUNCTION_TRACER, tracing_exam_2021::Building::info(), LOG_TRACER, tracing_exam_2021::Rentable::rent(), TRACER_OUTPUT_OFF, and TRACER_OUTPUT_ON.
Referenced by main().
app_exam_2021_2()
int app_exam_2021_2 ()
Definition at line 34 of file app_exam_2021_2.cpp.
                      {
    FUNCTION_TRACER;
    {
        BLOCK_TRACER("First block");
        LOG_TRACER("statement: const Person p1(\"Steve\");");
        Person p1("Steve"); // Note that this is tracing_example_exam::Person, not Vehicle::Person!
        LOG_TRACER("statement: Building b1(p1);");
        Building b1(p1);
        LOG_TRACER("statement: Building b2(*std::make_shared<Person>(std::move(p1)));");
        Building b2(*std::make_shared<Person>(std::move(p1)));
        LOG_TRACER("statement: Building* b3 = copy(new Building(Person(b2.getOwner())));");
        Building* b3 = copy(new Building(Person(b2.getOwner())));
        LOG_TRACER("statement: Building* b4 = b3;");
        Building* b4 = b3;
        LOG_TRACER("statement: b2 = *b3;");
        b2 = *b3;
        LOG_TRACER("statement: b3 = &b1;");
        b3 = &b1;
        LOG_TRACER("statement: b1 = b2;");
        b1 = b2;
        LOG_TRACER("statement: delete b4;");
        delete b4;
        LOG_TRACER("End of the first block");
    }
    {
        BLOCK_TRACER("Second block");
        try {
            BLOCK_TRACER("Try block");
            LOG_TRACER("statement: Person p1(\"Dave\");");
            Person p1("Dave");
            LOG_TRACER("statement: Person p2(\"Peter\");");
            Person p2("Peter");
            LOG_TRACER("statement: Person p3(\"Harry\");");
            Person p3("Harry");
            LOG_TRACER("statement: HolidayHome* h1 = new HolidayHome(p1, 2);");
            HolidayHome* h1 = new HolidayHome(p1, 2);
            LOG_TRACER("statement: const HolidayHome* h2 = h1;");
            const HolidayHome* h2 = h1;
            LOG_TRACER("statement: House h3 = copy(*h1);");
            House h3 = copy(*h1);
            LOG_TRACER("statement: auto h4 = copy(h2);");
            auto h4 = copy(h2);
            LOG_TRACER("statement: auto h5 = copy<const House*>(h2);");
            auto h5 = copy<const House*>(h2);
            LOG_TRACER("statement: f(*h1);");
            f(*h1);
            LOG_TRACER("statement: f(*h2);");
            f(*h2);
            LOG_TRACER("statement: f(h3);");
            f(h3);
            LOG_TRACER("statement: f(House(h3));");
            f(House(h3));
            LOG_TRACER("statement: h1->rent(p2);");
            h1->rent(p2);
            LOG_TRACER("statement: h1->rent(p3);");
            h1->rent(p3);
            LOG_TRACER("statement: h3.info();");
            h3.info();
            LOG_TRACER("statement: delete h1;");
            delete h1;
        } catch (std::runtime_error& e) {
            LOG_TRACER(e.what());
        }
        LOG_TRACER("End of the second block");
    }
    LOG_TRACER("statement: return 0;");
    return 0;
}
References BLOCK_TRACER, FUNCTION_TRACER, tracing_exam_2021::Building::getOwner(), tracing_exam_2021::Building::info(), LOG_TRACER, and tracing_exam_2021::Rentable::rent().
Referenced by main().
app_exam_2022_1()
int app_exam_2022_1 ()
Definition at line 18 of file app_exam_2022_1.cpp.
{
    FUNCTION_TRACER;
    LOG_TRACER("statement: Person p1(\"Steve\");");
    Person p1("Steve");
    LOG_TRACER("statement: Person p1(\"Peter\");");
    Person p2("Peter");
    LOG_TRACER("statement: auto b1 = std::make_unique<HolidayHome>(p1, 2);");
    auto b1 = std::make_unique<HolidayHome>(p1, 2);
    LOG_TRACER("statement: auto b2 = std::make_unique<House>(p2, 1);");
    auto b2 = std::make_unique<House>(p2, 1);
    LOG_TRACER("statement: *b2 = *b1;");
    *b2 = *b1;
    LOG_TRACER("statement: Road r1;");
    Road r1;
    LOG_TRACER("statement: r1.addBuilding(std::move(b1), 3);");
    r1.addBuilding(std::move(b1), 3);
    LOG_TRACER("statement: r1.addBuilding(std::move(b2), 1);");
    r1.addBuilding(std::move(b2), 1);
    LOG_TRACER("statement: Visitor v;");
    Visitor v;
    LOG_TRACER("statement: r1.welcome(v);");
    r1.welcome(v);
    LOG_TRACER("statement: Building& b3 = r1.getBuilding(1);");
    Building& b3 = r1.getBuilding(1);
    LOG_TRACER("statement: Building* b4 = &r1.getBuilding(3);");
    Building* b4 = &r1.getBuilding(3);
    LOG_TRACER("statement: b4 = &b3;");
    b4 = &b3;
    LOG_TRACER("statement: b4->welcome(v);");
    b4->welcome(v);
    LOG_TRACER("statement: r1.removeBuilding(3);");
    r1.removeBuilding(3);
    LOG_TRACER("statement: Road r2 = r1;");
    Road r2 = r1;
    LOG_TRACER("statement: r2.welcome(v);");
    r2.welcome(v);
    LOG_TRACER("statement: return 0;");
    return 0;
}
References tracing_exam_2022_1::Road::addBuilding(), FUNCTION_TRACER, tracing_exam_2022_1::Road::getBuilding(), LOG_TRACER, tracing_exam_2022_1::Road::removeBuilding(), tracing_exam_2022_1::Building::welcome(), and tracing_exam_2022_1::Road::welcome().
Referenced by main().
app_exam_2022_2()
int app_exam_2022_2 ()
Definition at line 18 of file app_exam_2022_2.cpp.
{
    FUNCTION_TRACER;
    try {
        BLOCK_TRACER("Try block");
        LOG_TRACER("statement: Visitor v;");
        Visitor v;
        LOG_TRACER("statement: Person p(\"Steve\");");
        Person p("Steve");
        LOG_TRACER("statement: auto b1 = std::make_unique<HolidayHome>(p, 2);");
        auto b1 = std::make_unique<HolidayHome>(p, 2);
        LOG_TRACER("statement: auto b2 = std::make_unique<House>(*b1);");
        auto b2 = std::make_unique<House>(*b1);
        LOG_TRACER("statement: Road r1;");
        Road r1;
        {
            BLOCK_TRACER("Observer block");
            LOG_TRACER("statement: auto roadObserver = std::make_shared<RoadObserver>();");
            auto roadObserver = std::make_shared<RoadObserver>();
            LOG_TRACER("statement: roadObserver->attach(&r1);");
            roadObserver->attach(&r1);
            LOG_TRACER("statement: auto rentingObserver = std::make_shared<RentableObserver>();");
            auto rentingObserver = std::make_shared<RentableObserver>();
            LOG_TRACER("statement: rentingObserver->attach(b1.get());");
            rentingObserver->attach(b1.get());
        }
        LOG_TRACER("statement: b1->rent(Person(\"Peter\"));");
        b1->rent(Person("Peter"));
        LOG_TRACER("statement: r1.addBuilding(std::move(b1), 1);");
        r1.addBuilding(std::move(b1), 1);
        LOG_TRACER("statement: r1.addBuilding(std::move(b2), 3);");
        r1.addBuilding(std::move(b2), 3);
        LOG_TRACER("statement: Building b3 = r1.getBuilding(3);");
        Building b3 = r1.getBuilding(3);
        LOG_TRACER("statement: Building& b4 = r1.getBuilding(1);");
        Building& b4 = r1.getBuilding(1);
        LOG_TRACER("r1.getBuilding(1) = b3;");
        r1.getBuilding(1) = b3;
        LOG_TRACER("statement: r1.welcome(v);");
        r1.welcome(v);
    } catch (std::runtime_error& e) {
        LOG_TRACER(e.what());
    }
    LOG_TRACER("statement: return 0;");
    return 0;
}
References tracing_exam_2022_2::Road::addBuilding(), BLOCK_TRACER, FUNCTION_TRACER, tracing_exam_2022_2::Road::getBuilding(), LOG_TRACER, and tracing_exam_2022_2::Road::welcome().
Referenced by main().
app_exception()
int app_exception ()
Demo prog for ctor/dtor features in class derivation.
Returns
status
Exceptions
None.
Definition at line 15 of file app_exception.cpp.
                    {
    FUNCTION_TRACER;
    try {
        BLOCK_TRACER("Try block");
        LOG_TRACER(" statement: Bicycle m1(\"Honda\", \"red\");");
        Bicycle m1("Honda", "red");
        LOG_TRACER(" statement: m1.get_nfo();");
        m1.info();
        LOG_TRACER(" statement: SailBoat s1(\"Marina\");");
        SailBoat s1("Marina");
        ;
        vector<double> direction(2);
        direction[0] = 1.0;
        direction[1] = -1.0;
        LOG_TRACER(" statement: s1.move(4, direction);");
        s1.move(4, direction);
        if (direction[0] == 1.0) {
            throw SailingException("Help");
        }
        LOG_TRACER(" statement: s1.startSinking();");
        s1.start_sinking();
        LOG_TRACER(" statement: s1.displayInfo();");
        s1.info();
    } catch (LoadingException& e) {
        LOG_TRACER(" catch clause with LoadingException");
        e.info();
    } catch (SailingException& e) {
        LOG_TRACER(" catch clause with SailingException");
        e.info();
    } catch (Exception& e) {
        LOG_TRACER(" catch clause with Exception");
        e.info();
        LOG_TRACER(e.what());
    }
    LOG_TRACER(" statement: return 0;");
    return 0;
}
References BLOCK_TRACER, FUNCTION_TRACER, Vehicles::Bicycle::info(), Vehicles::LoadingException::info(), Vehicles::SailBoat::info(), LOG_TRACER, Vehicles::SailBoat::move(), Vehicles::WaterVehicle::start_sinking(), and Vehicles::Exception::what().
Referenced by main().
app_fcalls()
int app_fcalls ()
Definition at line 34 of file app_fcalls.cpp.
                 {
    FUNCTION_TRACER;
    LOG_TRACER(" statement: Motorcycle bvar1(shared_ptr<Engine>(new Engine(1.0)));");
    Motorcycle bvar1(make_shared<Engine>(1.0));
    LOG_TRACER(" statement: f1(bvar1);");
    f1(bvar1);
    LOG_TRACER(" statement: f2(bvar1);");
    f2(bvar1);
    LOG_TRACER(" statement: f2p(&bvar1);");
    f2p(&bvar1);
    LOG_TRACER(" statement: f3(bvar1);");
    f3(bvar1);
    LOG_TRACER(" statement: f3p(&bvar1);");
    f3p(&bvar1);
    LOG_TRACER(" statement: g();");
    Motorcycle m;
    m = g();
    LOG_TRACER(" statement: return 0;");
    return 0;
}
References FUNCTION_TRACER, and LOG_TRACER.
Referenced by main().
app_hierarchies()
int app_hierarchies ()
Demo prog for ctor/dtor features in class derivation.
Returns
status
Exceptions
None.
Definition at line 13 of file app_hierarchies.cpp.
                      {
    FUNCTION_TRACER;
    LOG_TRACER(" statement: Bicycle m1(\"Honda\", \"red\");");
    Bicycle m1("Honda", "red");
    LOG_TRACER(" statement: m1.displayInfo();");
    m1.info();
    LOG_TRACER(" statement: Bicycle m2(m1);");
    Bicycle m2(m1);
    LOG_TRACER(" statement: m2.addPassenger();");
    m2.add_passenger();
    LOG_TRACER(" statement: m2.displayInfo();");
    m2.info();
    LOG_TRACER(" statement: Bicycle* m3Ptr = new Bicycle(m2);");
    auto m3Ptr = new Bicycle(m2);
    LOG_TRACER(" statement: m3Ptr->displayInfo()");
    m3Ptr->info();
    LOG_TRACER(" statement: m2 = m1;");
    m2 = m1;
    LOG_TRACER(" statement: delete m3Ptr;");
    delete m3Ptr;
    LOG_TRACER(" statement: SailBoat s1(\"Marina\");");
    SailBoat s1("Marina");
    LOG_TRACER(" statement: SailBoat s1(\"Freddy\");");
    SailBoat s2("Freddy");
    vector<double> direction(2);
    direction[0] = 1.0;
    direction[1] = -1.0;
    LOG_TRACER(" statement: s1.move(4, direction);");
    s1.move(4, direction);
    LOG_TRACER(" statement: s1.startSinking();");
    s1.start_sinking();
    LOG_TRACER(" statement: s1.displayInfo();");
    s1.info();
    LOG_TRACER(" statement: Vehicle* v1Ptr = &s1;");
    Vehicle* v1Ptr = &s1;
    LOG_TRACER(" statement: v1Ptr->displayInfo();");
    v1Ptr->info();
    LOG_TRACER(" statement: s2 = s1;");
    s2 = s1;
    LOG_TRACER(" statement: s2.displayInfo();");
    s2.info();
    // The following won't compile because WaterVehicle has pure virtual
    // functions.
    // WaterVehicle wv1(s1);
    LOG_TRACER(" statement: return 0;");
    return 0;
}
References Vehicles::PassengerRoadVehicle::add_passenger(), FUNCTION_TRACER, Vehicles::Vehicle::info(), Vehicles::Bicycle::info(), Vehicles::SailBoat::info(), LOG_TRACER, Vehicles::SailBoat::move(), and Vehicles::WaterVehicle::start_sinking().
Referenced by main().
app_poly1()
int app_poly1 ()
Demonstrates late binding.
Returns
status
Exceptions
None.
Definition at line 29 of file app_poly1.cpp.
                {
    FUNCTION_TRACER;
    TRACER_OUTPUT_OFF; // Setting the log output ON/OFF
    list<shared_ptr<Vehicle>> l1{make_shared<RoadVehicle>(), make_shared<RoadVehicle>(),
                                 make_shared<PassengerRoadVehicle>(5)};
    TRACER_OUTPUT_ON; // Setting the log output ON/OFF
    LOG_TRACER("invocation for l1:");
    display_all(l1);
    LOG_TRACER("done with l1.");
    TRACER_OUTPUT_OFF; // Setting the log output ON/OFF
    list<shared_ptr<Vehicle>> l2{make_shared<RoadVehicle>(), make_shared<Bicycle>("Honda", "black"),
                                 make_shared<SailBoat>("Freddy")};
    TRACER_OUTPUT_ON; // Setting the log output ON/OFF
    LOG_TRACER("invocation for l2:");
    display_all(l2);
    LOG_TRACER("done with l2.");
    LOG_TRACER(">>>> statement: return 0;");
    return 0;
}
References FUNCTION_TRACER, LOG_TRACER, TRACER_OUTPUT_OFF, and TRACER_OUTPUT_ON.
Referenced by main().
app_poly2()
int app_poly2 ()
Demonstrates late binding.
Returns
status
Exceptions
None.
Definition at line 28 of file app_poly2.cpp.
                {
    FUNCTION_TRACER;
    // Setting the log output ON/OFF
    TRACER_OUTPUT_OFF;
    LOG_TRACER(">>>> statement: RoadVehicle rv1;");
    RoadVehicle rv1;
    LOG_TRACER(">>>> statement: Bicycle m1(\"Honda\", \"black\");");
    Bicycle m1("Honda", "black");
    LOG_TRACER(">>>> statement: PassengerRoadVehicle prv1(5);");
    PassengerRoadVehicle prv1(5);
    LOG_TRACER(">>>> statement: SailBoat b1(\"Freddy\");");
    SailBoat b1("Freddy");
    // Setting the log output ON/OFF
    TRACER_OUTPUT_ON;
    LOG_TRACER(">>>> statement: displayBis(rv1);");
    displayBis(rv1);
    LOG_TRACER(">>>> statement: displayBis(m1);");
    displayBis(m1);
    LOG_TRACER(">>>> statement: displayBis(prv1);");
    displayBis(prv1);
    LOG_TRACER(">>>> statement: displayBis(b1);");
    displayBis(b1);
    LOG_TRACER(">>>> statement: auto rv2Ptr = new RoadVehicle();");
    auto rv2Ptr = new RoadVehicle();
    LOG_TRACER(" statement: Bicycle* m1Ptr = &m1;");
    Bicycle* m1Ptr = &m1;
    LOG_TRACER(" statement: auto prv2Ptr = new PassengerRoadVehicle(10);");
    auto prv2Ptr = new PassengerRoadVehicle(10);
    LOG_TRACER(">>>> statement: SailBoat* b1Ptr = &b1;");
    auto b1Ptr = &b1;
    LOG_TRACER(">>>> statement: display(rv2Ptr);");
    display(rv2Ptr);
    LOG_TRACER(">>>> statement: display(m1Ptr);");
    display(m1Ptr);
    LOG_TRACER(">>>> statement: displayBis(m1);");
    displayBis(m1);
    LOG_TRACER(">>>> statement: display(prv2Ptr);");
    display(prv2Ptr);
    LOG_TRACER(">>>> statement: display(b1Ptr);");
    display(b1Ptr);
    // delete b1Ptr;
    // Runtime error because of assignment b1Ptr = &b1;
    // So b1Ptr points to local variable that should not be deleted
    // Should have been:
    // delete b1Ptr; b1Ptr = &b1s;
    // in the code a couple of lines earlier.
    // Notice the dynamically allocated object do NOT get destructed: memory
    // leakage.
    LOG_TRACER(">>>> statement: return 0;");
    return 0;
}
References FUNCTION_TRACER, LOG_TRACER, TRACER_OUTPUT_OFF, and TRACER_OUTPUT_ON.
Referenced by main().