Gobelijn API documentation: tracing_example_exam::House Class Reference
tracing_example_exam::House Class Reference
#include <House.h>
Public Member Functions
House (Person owner, unsigned int bedrooms)
Constructor.
virtual ~House ()
Destructor.
House (const House &h)
Copy Constructor.
House (House &&h)
Move Constructor.
House & operator= (const House &)
Copy-assignment of a House:
House & operator= (House &&)
Move-assignment of a House:
virtual std::string getName () const override
Returns the name of the Building.
virtual void addNeighbour (House *neighbour)
Adds a House to the list of neighbours of the current House It does not take ownership of this neighbouring House.
Public Member Functions inherited from tracing_example_exam::Building
Building (Person &owner)
Constructor.
Building (const Person &owner)
Constructor.
Building (Person &&owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual Person & getOwner ()
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
Adds a Building to the list of neighbours of the current building It does not take ownership of this neighbouring Building.
Private Attributes
std::shared_ptr< const BathRoom > m_bathroom = std::make_shared<const BathRoom>()
Kitchen m_kitchen
Additional Inherited Members
Protected Attributes inherited from tracing_example_exam::Building
std::vector< std::shared_ptr< const Room > > m_rooms
std::vector< Building * > m_neighbours
Person m_owner
Detailed Description
Definition at line 19 of file House.h.
Constructor & Destructor Documentation
House() [1/3]
tracing_example_exam::House::House (Person owner, unsigned int bedrooms)
Constructor.
Definition at line 17 of file House.cpp.
References COMP_MISC_MEMBER_TRACER, m_bathroom, and tracing_example_exam::Building::m_rooms.
~House()
tracing_example_exam::House::~House () virtual
Destructor.
Definition at line 59 of file House.cpp.
References COMP_MISC_MEMBER_TRACER.
House() [2/3]
tracing_example_exam::House::House (const House & h)
Copy Constructor.
Definition at line 27 of file House.cpp.
References COMP_MISC_MEMBER_TRACER.
House() [3/3]
tracing_example_exam::House::House (House && h)
Move Constructor.
Definition at line 32 of file House.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
House & tracing_example_exam::House::operator= (const House & other)
Copy-assignment of a House:
Definition at line 37 of file House.cpp.
References COMP_MISC_MEMBER_TRACER, m_bathroom, m_kitchen, and tracing_example_exam::Building::operator=().
Referenced by tracing_example_exam::HolidayHome::operator=().
operator=() [2/2]
House & tracing_example_exam::House::operator= (House && other)
Move-assignment of a House:
Definition at line 48 of file House.cpp.
References COMP_MISC_MEMBER_TRACER, m_bathroom, m_kitchen, and tracing_example_exam::Building::operator=().
getName()
std::string tracing_example_exam::House::getName () const override virtual
Returns the name of the Building.
Reimplemented from tracing_example_exam::Building.
Reimplemented in tracing_example_exam::HolidayHome.
Definition at line 61 of file House.cpp.
References COMP_MISC_MEMBER_TRACER.
addNeighbour()
void tracing_example_exam::House::addNeighbour (House * neighbour) virtual
Adds a House to the list of neighbours of the current House It does not take ownership of this neighbouring House.
Definition at line 67 of file House.cpp.
References COMP_MISC_MEMBER_TRACER, and tracing_example_exam::Building::m_neighbours.
Member Data Documentation
m_bathroom
std::shared_ptr<const BathRoom> tracing_example_exam::House::m_bathroom = std::make_shared<const BathRoom>() private
Definition at line 48 of file House.h.
Referenced by House(), and operator=().
m_kitchen
Kitchen tracing_example_exam::House::m_kitchen private
Definition at line 49 of file House.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
House.h
House.cpp