Gobelijn API documentation: tracing_example_exam::HolidayHome Class Reference
tracing_example_exam::HolidayHome Class Reference
#include <HolidayHome.h>
Public Member Functions
HolidayHome (Person &owner, unsigned int bedrooms)
Constructor.
HolidayHome (const HolidayHome &h)
Copy Constructor.
HolidayHome (HolidayHome &&h)
Move Constructor.
virtual ~HolidayHome ()
Destructor.
HolidayHome & operator= (const HolidayHome &)
Copy-assignment of a HolidayHome:
HolidayHome & operator= (HolidayHome &&)
Move-assignment of a HolidayHome:
virtual std::string getName () const override
Returns the name of the Building.
virtual void addNeighbour (HolidayHome *neighbour)
Adds a HolidayHome to the list of neighbours of the current House It does not take ownership of this neighbouring HolidayHome.
Public Member Functions inherited from tracing_example_exam::House
House (Person owner, unsigned int bedrooms)
Constructor.
virtual ~House ()
Destructor.
House (const House &h)
Copy Constructor.
House (House &&h)
Move Constructor.
House & operator= (const House &)
Copy-assignment of a House:
House & operator= (House &&)
Move-assignment of a House:
virtual void addNeighbour (House *neighbour)
Adds a House to the list of neighbours of the current House It does not take ownership of this neighbouring House.
Public Member Functions inherited from tracing_example_exam::Building
Building (Person &owner)
Constructor.
Building (const Person &owner)
Constructor.
Building (Person &&owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual Person & getOwner ()
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
Adds a Building to the list of neighbours of the current building It does not take ownership of this neighbouring Building.
Public Member Functions inherited from tracing_example_exam::Rentable
Rentable ()
Constructor.
Rentable (const Rentable &r)
Copy Constructor.
Rentable (Rentable &&r)
Move Constructor.
virtual ~Rentable ()
Destructor.
Rentable & operator= (const Rentable &)
Copy-assignment of a Rentable:
Rentable & operator= (Rentable &&)
Move-assignment of a Rentable:
void rent (Person &renter)
Rent this Rentable.
Additional Inherited Members
Protected Attributes inherited from tracing_example_exam::Building
std::vector< std::shared_ptr< const Room > > m_rooms
std::vector< Building * > m_neighbours
Person m_owner
Detailed Description
Definition at line 16 of file HolidayHome.h.
Constructor & Destructor Documentation
HolidayHome() [1/3]
tracing_example_exam::HolidayHome::HolidayHome (Person & owner, unsigned int bedrooms)
Constructor.
Definition at line 12 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER.
HolidayHome() [2/3]
tracing_example_exam::HolidayHome::HolidayHome (const HolidayHome & h)
Copy Constructor.
Definition at line 16 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER.
HolidayHome() [3/3]
tracing_example_exam::HolidayHome::HolidayHome (HolidayHome && h)
Move Constructor.
Definition at line 18 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER.
~HolidayHome()
tracing_example_exam::HolidayHome::~HolidayHome () virtual
Destructor.
Definition at line 14 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
HolidayHome & tracing_example_exam::HolidayHome::operator= (const HolidayHome & other)
Copy-assignment of a HolidayHome:
Definition at line 20 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER, tracing_example_exam::House::operator=(), and tracing_example_exam::Rentable::operator=().
operator=() [2/2]
HolidayHome & tracing_example_exam::HolidayHome::operator= (HolidayHome && other)
Move-assignment of a HolidayHome:
Definition at line 30 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER, tracing_example_exam::House::operator=(), and tracing_example_exam::Rentable::operator=().
getName()
std::string tracing_example_exam::HolidayHome::getName () const override virtual
Returns the name of the Building.
Reimplemented from tracing_example_exam::House.
Definition at line 40 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER.
addNeighbour()
void tracing_example_exam::HolidayHome::addNeighbour (HolidayHome * neighbour) virtual
Adds a HolidayHome to the list of neighbours of the current House It does not take ownership of this neighbouring HolidayHome.
Definition at line 46 of file HolidayHome.cpp.
References COMP_MISC_MEMBER_TRACER, and tracing_example_exam::Building::m_neighbours.
Referenced by app_example_exam_2021_1().
The documentation for this class was generated from the following files:
HolidayHome.h
HolidayHome.cpp