Gobelijn API documentation: stack3.cpp File Reference
stack3.cpp File Reference
Using the class template with default parameters.
#include "stack3.hpp"
#include <deque>
#include <iostream>
Functions
int main ()
Detailed Description
Using the class template with default parameters.
Author
J. Broeckhove, CoMP/UA - see copyright.txt
Definition in file stack3.cpp.
Function Documentation
main()
int main ()
Definition at line 12 of file stack3.cpp.
References Stack< T >::pop(), Stack< T >::push(), and Stack< T >::top().