Gobelijn API documentation: Range.h File Reference
Range.h File Reference
Range (see also boost Range library)
#include <iostream>
Classes
struct Range< Iter >
Range needs to be a specific type so we can overload some operators (e.g.
Functions
template<typename Iter >
Range< Iter > make_range (Iter it1, Iter it2)
template<typename Cont >
Range< typename Cont::const_iterator > make_range (Cont const &c)
template<typename T , typename U >
std::ostream & operator<< (std::ostream &out, std::pair< T, U > const &p)
template<typename Iter >
std::ostream & operator<< (std::ostream &out, Range< Iter > r)
Detailed Description
Range (see also boost Range library)
Definition in file Range.h.
Function Documentation
make_range() [1/2]
template<typename Iter > Range< Iter > make_range (Iter it1, Iter it2)
Definition at line 34 of file Range.h.
Referenced by main().
make_range() [2/2]
template<typename Cont > Range< typename Cont::const_iterator > make_range (Cont const & c)
Definition at line 40 of file Range.h.
operator<<() [1/2]
template<typename T , typename U > std::ostream & operator<< (std::ostream & out, std::pair< T, U > const & p)
Definition at line 46 of file Range.h.
References operator<<().
Referenced by operator<<().
operator<<() [2/2]
template<typename Iter > std::ostream & operator<< (std::ostream & out, Range< Iter > r)
Definition at line 54 of file Range.h.