Gobelijn API documentation: app_exec.cpp File Reference
app_exec.cpp File Reference
Driver to select routines.
#include "demos.h"
#include "tclap/CmdLine.h"
#include "util/Exception.h"
#include <g3log/g3log.hpp>
#include <g3log/logworker.hpp>
Functions
int main (int argc, char *argv[])
Detailed Description
Driver to select routines.
Author
Jan Broeckhove, CoMP/UA
Definition in file app_exec.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 39 of file app_exec.cpp.
References app_copy(), app_essentialops(), app_example_exam_2021_1(), app_example_exam_2021_2(), app_exception(), app_fcalls(), app_hierarchies(), app_poly1(), and app_poly2().