Gobelijn API documentation: tracing_example_exam::Building Class Reference
tracing_example_exam::Building Class Reference
#include <Building.h>
Public Member Functions
Building (Person &owner)
Constructor.
Building (const Person &owner)
Constructor.
Building (Person &&owner)
Constructor.
Building (const Building &b)
Copy Constructor.
Building (Building &&b)
Move Constructor.
Building & operator= (const Building &)
Copy-assignment of a Building:
Building & operator= (Building &&)
Move-assignment of a Building:
virtual ~Building ()
Destructor.
virtual void info () const
Prints building information.
virtual std::string getName () const
Returns the name of the Building.
virtual Person & getOwner ()
Returns the Person who owns the building.
virtual void addNeighbour (Building *neighbour)
Adds a Building to the list of neighbours of the current building It does not take ownership of this neighbouring Building.
Protected Attributes
std::vector< std::shared_ptr< const Room > > m_rooms
std::vector< Building * > m_neighbours
Person m_owner
Detailed Description
Definition at line 19 of file Building.h.
Constructor & Destructor Documentation
Building() [1/5]
tracing_example_exam::Building::Building (Person & owner)
Constructor.
Definition at line 15 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER.
Building() [2/5]
tracing_example_exam::Building::Building (const Person & owner)
Constructor.
Definition at line 17 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER.
Building() [3/5]
tracing_example_exam::Building::Building (Person && owner)
Constructor.
Definition at line 19 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER.
Building() [4/5]
tracing_example_exam::Building::Building (const Building & b)
Copy Constructor.
Definition at line 21 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER, and m_rooms.
Building() [5/5]
tracing_example_exam::Building::Building (Building && b)
Move Constructor.
Definition at line 27 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER, m_neighbours, and m_rooms.
~Building()
tracing_example_exam::Building::~Building () virtual
Destructor.
Definition at line 36 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
Building & tracing_example_exam::Building::operator= (const Building & other)
Copy-assignment of a Building:
Definition at line 38 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER, m_neighbours, m_owner, and m_rooms.
Referenced by tracing_example_exam::House::operator=().
operator=() [2/2]
Building & tracing_example_exam::Building::operator= (Building && other)
Move-assignment of a Building:
Definition at line 49 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER, m_neighbours, m_owner, and m_rooms.
info()
void tracing_example_exam::Building::info () const virtual
Prints building information.
Definition at line 62 of file Building.cpp.
References COMP_MISC_LOG_TRACER, COMP_MISC_MEMBER_TRACER, getName(), m_neighbours, and m_rooms.
Referenced by app_example_exam_2021_1(), and app_example_exam_2021_2().
getName()
std::string tracing_example_exam::Building::getName () const virtual
Returns the name of the Building.
Reimplemented in tracing_example_exam::HolidayHome, and tracing_example_exam::House.
Definition at line 72 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER.
Referenced by info().
getOwner()
Person & tracing_example_exam::Building::getOwner () virtual
Returns the Person who owns the building.
Definition at line 78 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER, and m_owner.
Referenced by app_example_exam_2021_2().
addNeighbour()
void tracing_example_exam::Building::addNeighbour (Building * neighbour) virtual
Adds a Building to the list of neighbours of the current building It does not take ownership of this neighbouring Building.
Definition at line 84 of file Building.cpp.
References COMP_MISC_MEMBER_TRACER, and m_neighbours.
Referenced by app_example_exam_2021_1().
Member Data Documentation
m_rooms
std::vector<std::shared_ptr<const Room> > tracing_example_exam::Building::m_rooms protected
Definition at line 60 of file Building.h.
Referenced by Building(), tracing_example_exam::House::House(), info(), and operator=().
m_neighbours
std::vector<Building*> tracing_example_exam::Building::m_neighbours protected
Definition at line 61 of file Building.h.
Referenced by Building(), addNeighbour(), tracing_example_exam::HolidayHome::addNeighbour(), tracing_example_exam::House::addNeighbour(), info(), and operator=().
m_owner
Person tracing_example_exam::Building::m_owner protected
Definition at line 62 of file Building.h.
Referenced by getOwner(), and operator=().
The documentation for this class was generated from the following files:
Building.h
Building.cpp