Gobelijn API documentation: stack2.cpp File Reference
stack2.cpp File Reference
Client niet bewust van specialisatie.
#include "stack2.hpp"
#include <iostream>
Functions
int main ()
Detailed Description
Client niet bewust van specialisatie.
Author
J. Broeckhove - see copyright.txt
Definition in file stack2.cpp.
Function Documentation
main()
int main ()
Definition at line 11 of file stack2.cpp.
References Stack< std::string >::pop(), Stack< std::string >::push(), and Stack< std::string >::top().