Gobelijn API documentation: sum1.cpp File Reference
sum1.cpp File Reference
Sum elements of container, first attempt.
#include "Range.h"
#include <list>
#include <vector>
Functions
template<typename C >
C::value_type sum (C const &c)
int main ()
Detailed Description
Sum elements of container, first attempt.
Definition in file sum1.cpp.
Function Documentation
sum()
template<typename C > C::value_type sum (C const & c)
Definition at line 26 of file sum1.cpp.
Referenced by UA_CoMP::Num::AdaptiveQuadrature< QuadRule1, QuadRule2, ConvergencePolicy, CellCountPolicy >::evaluate(), main(), and UA_CoMP::Num::Bisector< Rule >::sum().
main()
int main ()
Definition at line 35 of file sum1.cpp.
References make_range(), and sum().