Gobelijn API documentation: ODemo::RoadVehicle Class Reference
ODemo::RoadVehicle Class Reference
A RoadVehicle is any kind of vehicle that moves on the road.
#include <RoadVehicle.h>
Public Member Functions
RoadVehicle ()
Default constructor.
RoadVehicle (const RoadVehicle &ori)
Copy constructor.
RoadVehicle (RoadVehicle &&ori) noexcept
Move constructor.
RoadVehicle & operator= (const RoadVehicle &rhs)
Copy assignment operator.
RoadVehicle & operator= (RoadVehicle &&rhs) noexcept
Move assignment operator.
~RoadVehicle () override
Destructor.
void info () const override
Return identification info.
void move (double speed, std::vector< double > direction) override
Motion of the vehicle.
Public Member Functions inherited from ODemo::LandVehicle
LandVehicle ()
default constructor.
LandVehicle (const LandVehicle &ori)
Copy constructor.
LandVehicle (LandVehicle &&ori) noexcept
Move constructor.
LandVehicle & operator= (const LandVehicle &rhs)
Copy assignment.
LandVehicle & operator= (LandVehicle &&rhs) noexcept
Move assignment.
~LandVehicle () override
Destructor.
Public Member Functions inherited from ODemo::Vehicle
virtual ~Vehicle ()=default
Destructor.
Detailed Description
A RoadVehicle is any kind of vehicle that moves on the road.
Definition at line 16 of file RoadVehicle.h.
Constructor & Destructor Documentation
RoadVehicle() [1/3]
ODemo::RoadVehicle::RoadVehicle ()
Default constructor.
Definition at line 14 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
RoadVehicle() [2/3]
ODemo::RoadVehicle::RoadVehicle (const RoadVehicle & ori)
Copy constructor.
Definition at line 16 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
RoadVehicle() [3/3]
ODemo::RoadVehicle::RoadVehicle (RoadVehicle && ori) noexcept
Move constructor.
Definition at line 18 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
~RoadVehicle()
ODemo::RoadVehicle::~RoadVehicle () override
Destructor.
Definition at line 38 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
Member Function Documentation
operator=() [1/2]
RoadVehicle & ODemo::RoadVehicle::operator= (const RoadVehicle & rhs)
Copy assignment operator.
Definition at line 20 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and ODemo::LandVehicle::operator=().
Referenced by ODemo::PassengerRoadVehicle::operator=().
operator=() [2/2]
RoadVehicle & ODemo::RoadVehicle::operator= (RoadVehicle && rhs) noexcept
Move assignment operator.
Definition at line 29 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER, and ODemo::LandVehicle::operator=().
info()
void ODemo::RoadVehicle::info () const override virtual
Return identification info.
Reimplemented from ODemo::LandVehicle.
Definition at line 40 of file RoadVehicle.cpp.
References COMP_MISC_LOG_TRACER, and COMP_MISC_MEMBER_TRACER.
move()
void ODemo::RoadVehicle::move (double speed, std::vector< double > direction) override virtual
Motion of the vehicle.
Implements ODemo::LandVehicle.
Definition at line 47 of file RoadVehicle.cpp.
References COMP_MISC_MEMBER_TRACER.
The documentation for this class was generated from the following files:
RoadVehicle.h
RoadVehicle.cpp