Gobelijn API documentation: UA_CoMP::Util::StringUtils Class Reference
UA_CoMP::Util::StringUtils Class Reference
String utilities.
#include <StringUtils.h>
Static Public Member Functions
template<typename T >
static T FromString (std::string const &s)
Builds a value of type T representation from a string.
template<typename T >
static std::string ToString (T const &value)
Builds a string representation of a value of type T.
static std::string ToUpper (std::string const &source)
Builds a string with upper case characters only.
static std::string TrimRight (std::string const &source, std::string const &t=" ")
Trim characters at right end of string.
static std::string TrimLeft (std::string const &source, std::string const &t=" ")
Trim characters at left end of string.
static std::string Trim (std::string const &source, std::string const &t=" ")
Trim characters at both ends of string.
Detailed Description
String utilities.
Definition at line 33 of file StringUtils.h.
Member Function Documentation
FromString()
template<typename T > static T UA_CoMP::Util::StringUtils::FromString (std::string const & s) inline static
Builds a value of type T representation from a string.
Definition at line 38 of file StringUtils.h.
ToString()
template<typename T > static std::string UA_CoMP::Util::StringUtils::ToString (T const & value) inline static
Builds a string representation of a value of type T.
Definition at line 48 of file StringUtils.h.
Referenced by ODemo::PassengerRoadVehicle::info().
ToUpper()
static std::string UA_CoMP::Util::StringUtils::ToUpper (std::string const & source) inline static
Builds a string with upper case characters only.
Definition at line 56 of file StringUtils.h.
TrimRight()
static std::string UA_CoMP::Util::StringUtils::TrimRight (std::string const & source, std::string const & t = " ") inline static
Trim characters at right end of string.
Definition at line 65 of file StringUtils.h.
Referenced by Trim().
TrimLeft()
static std::string UA_CoMP::Util::StringUtils::TrimLeft (std::string const & source, std::string const & t = " ") inline static
Trim characters at left end of string.
Definition at line 72 of file StringUtils.h.
Referenced by Trim().
Trim()
static std::string UA_CoMP::Util::StringUtils::Trim (std::string const & source, std::string const & t = " ") inline static
Trim characters at both ends of string.
Definition at line 79 of file StringUtils.h.
References TrimLeft(), and TrimRight().
The documentation for this class was generated from the following file:
StringUtils.h